<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-02">
<meta name="keywords" content="generative artificial intelligence, knowledge construction, learner-in-the-loop, writing-to-learn, metacognition, self-regulated learning, personal wiki, cognitive offloading, AI in education">

<title>From Notes to Knowledge: Designing an AI Wiki Companion for Learner-in-the-Loop Knowledge Construction – AI Research Portal</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-21bc5de5f9a4680d84de3225bdbd563f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<script>
  // Initialize Mermaid with startOnLoad disabled
  mermaid.initialize({ 
    startOnLoad: false,
    theme: 'default',
    securityLevel: 'loose'
  });
  
  // Convert Quarto's mermaid code blocks and render them
  document.addEventListener('DOMContentLoaded', async function() {
    console.log('[Mermaid] Script starting...');
    
    try {
      // Convert <pre class="mermaid"><code> to <div class="mermaid">
      var mermaidDivs = [];
      var preElements = document.querySelectorAll('pre.mermaid');
      console.log('[Mermaid] Found', preElements.length, 'pre.mermaid elements');
      
      preElements.forEach(function(pre, index) {
        var code = pre.querySelector('code');
        if (code) {
          var div = document.createElement('div');
          div.className = 'mermaid';
          div.textContent = code.textContent;
          pre.parentNode.replaceChild(div, pre);
          mermaidDivs.push(div);
          console.log('[Mermaid] Converted diagram', index + 1, ':', code.textContent.substring(0, 50));
        }
      });
      
      // Render all converted diagrams
      if (mermaidDivs.length > 0) {
        console.log('[Mermaid] Rendering', mermaidDivs.length, 'diagrams...');
        await mermaid.run({ 
          nodes: mermaidDivs,
          suppressErrors: false
        });
        console.log('[Mermaid] Rendering complete');
      } else {
        console.log('[Mermaid] No diagrams found to render');
      }
    } catch (error) {
      console.error('[Mermaid] Error:', error);
    }
  });
</script>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&amp;display=swap" rel="stylesheet">

<style>
  body {
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  }
  
  /* Smooth scrolling */
  html {
    scroll-behavior: smooth;
  }
  
  /* Custom scrollbar */
  ::-webkit-scrollbar {
    width: 10px;
  }
  
  ::-webkit-scrollbar-track {
    background: #f1f5f9;
  }
  
  ::-webkit-scrollbar-thumb {
    background: linear-gradient(135deg, #3b82f6, #2563eb);
    border-radius: 5px;
  }
  
  ::-webkit-scrollbar-thumb:hover {
    background: linear-gradient(135deg, #2563eb, #1e40af);
  }
</style>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">AI Research Portal</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">🏠 Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-topics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">📚 Topics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-topics">    
        <li>
    <a class="dropdown-item" href="../topics/ai-agents.html">
 <span class="dropdown-text">🤖 AI Agents</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../topics/llm-reasoning.html">
 <span class="dropdown-text">🧠 LLM Reasoning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../topics/rag-retrieval.html">
 <span class="dropdown-text">🔍 RAG &amp; Retrieval</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../topics/multi-modal.html">
 <span class="dropdown-text">🎬 Multi-Modal</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-papers" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">📄 Papers</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-papers">    
        <li>
    <a class="dropdown-item" href="../global-search.html">
 <span class="dropdown-text">🔍 Global Search</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../reading-list.html">
 <span class="dropdown-text">📋 Reading List</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../notes.html">
 <span class="dropdown-text">📝 My Notes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../compare-papers.html">
 <span class="dropdown-text">⚖️ Compare Papers</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-knowledge" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🧠 Knowledge</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-knowledge">    
        <li>
    <a class="dropdown-item" href="../wiki.html">
 <span class="dropdown-text">📖 Wiki</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../wiki-graph.html">
 <span class="dropdown-text">🕸️ Knowledge Graph</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../concept-explorer.html">
 <span class="dropdown-text">🗺️ Concept Explorer</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../recommendations.html">
 <span class="dropdown-text">💡 Recommendations</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analytics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">📊 Analytics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analytics">    
        <li>
    <a class="dropdown-item" href="../statistics.html">
 <span class="dropdown-text">📈 Statistics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tag-cloud.html">
 <span class="dropdown-text">🏷️ Tag Cloud</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../authors.html">
 <span class="dropdown-text">👥 Authors</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../digests/index.html">
 <span class="dropdown-text">📰 Weekly Digests</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">From Notes to Knowledge: Designing an AI Wiki Companion for Learner-in-the-Loop Knowledge Construction</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">📚 Research Topics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/ai-agents.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🤖 AI Agents</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/llm-reasoning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🧠 LLM Reasoning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/rag-retrieval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🔍 RAG &amp; Retrieval</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../topics/multi-modal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🎬 Multi-Modal</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">🔬 Research Tools</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../global-search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🔍 Global Search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../search-papers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📄 Search Papers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reading-list.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📋 Reading List</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📝 My Notes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../compare-papers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">⚖️ Compare Papers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../recommendations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">💡 Recommendations</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">🧠 Knowledge Base</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../wiki.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📖 Wiki</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../wiki-graph.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🕸️ Knowledge Graph</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../concept-explorer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🗺️ Concept Explorer</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../concepts/glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📚 Glossary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../concepts/connections.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🔗 Connections</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../concepts/papers-by-concept.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📄 Papers by Concept</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">📊 Analytics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📈 Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../tag-cloud.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🏷️ Tag Cloud</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../authors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">👥 Authors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../digests/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📰 Weekly Digests</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">🎯 Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../learning-paths.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🛤️ Learning Paths</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../must-read-papers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">⭐ Must-Read Papers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../research-workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">🔄 Research Workflow</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../rss.xml" class="sidebar-item-text sidebar-link">
 <span class="menu-text">📡 RSS Feed</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#conference-paper" id="toc-conference-paper" class="nav-link active" data-scroll-target="#conference-paper">📄 Conference Paper</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">1. Introduction</a>
  <ul class="collapse">
  <li><a href="#from-information-access-to-knowledge-construction" id="toc-from-information-access-to-knowledge-construction" class="nav-link" data-scroll-target="#from-information-access-to-knowledge-construction">1.1 From Information Access to Knowledge Construction</a></li>
  <li><a href="#personal-wikis-as-environments-for-developing-knowledge" id="toc-personal-wikis-as-environments-for-developing-knowledge" class="nav-link" data-scroll-target="#personal-wikis-as-environments-for-developing-knowledge">1.2 Personal Wikis as Environments for Developing Knowledge</a></li>
  <li><a href="#from-ai-content-generation-to-ai-supported-knowledge-construction" id="toc-from-ai-content-generation-to-ai-supported-knowledge-construction" class="nav-link" data-scroll-target="#from-ai-content-generation-to-ai-supported-knowledge-construction">1.3 From AI Content Generation to AI-Supported Knowledge Construction</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">1.4 Research Questions</a></li>
  </ul></li>
  <li><a href="#theoretical-background-and-related-work" id="toc-theoretical-background-and-related-work" class="nav-link" data-scroll-target="#theoretical-background-and-related-work">2. Theoretical Background and Related Work</a>
  <ul class="collapse">
  <li><a href="#writing-to-learn-and-active-knowledge-construction" id="toc-writing-to-learn-and-active-knowledge-construction" class="nav-link" data-scroll-target="#writing-to-learn-and-active-knowledge-construction">2.1 Writing-to-Learn and Active Knowledge Construction</a></li>
  <li><a href="#metacognition-and-self-regulated-learning" id="toc-metacognition-and-self-regulated-learning" class="nav-link" data-scroll-target="#metacognition-and-self-regulated-learning">2.2 Metacognition and Self-Regulated Learning</a></li>
  <li><a href="#personal-wikis-and-networked-knowledge-environments" id="toc-personal-wikis-and-networked-knowledge-environments" class="nav-link" data-scroll-target="#personal-wikis-and-networked-knowledge-environments">2.3 Personal Wikis and Networked Knowledge Environments</a></li>
  <li><a href="#generative-ai-as-formative-and-metacognitive-scaffolding" id="toc-generative-ai-as-formative-and-metacognitive-scaffolding" class="nav-link" data-scroll-target="#generative-ai-as-formative-and-metacognitive-scaffolding">2.4 Generative AI as Formative and Metacognitive Scaffolding</a></li>
  <li><a href="#learner-in-the-loop-knowledge-construction" id="toc-learner-in-the-loop-knowledge-construction" class="nav-link" data-scroll-target="#learner-in-the-loop-knowledge-construction">2.5 Learner-in-the-Loop Knowledge Construction</a></li>
  <li><a href="#cognitive-offloading-and-the-risk-of-substitution" id="toc-cognitive-offloading-and-the-risk-of-substitution" class="nav-link" data-scroll-target="#cognitive-offloading-and-the-risk-of-substitution">2.6 Cognitive Offloading and the Risk of Substitution</a></li>
  <li><a href="#research-gap-and-theoretical-contribution" id="toc-research-gap-and-theoretical-contribution" class="nav-link" data-scroll-target="#research-gap-and-theoretical-contribution">2.7 Research Gap and Theoretical Contribution</a></li>
  </ul></li>
  <li><a href="#proposed-ai-wiki-companion" id="toc-proposed-ai-wiki-companion" class="nav-link" data-scroll-target="#proposed-ai-wiki-companion">3. Proposed AI Wiki Companion</a>
  <ul class="collapse">
  <li><a href="#design-rationale" id="toc-design-rationale" class="nav-link" data-scroll-target="#design-rationale">3.1 Design Rationale</a></li>
  <li><a href="#ai-supported-knowledge-construction-cycle" id="toc-ai-supported-knowledge-construction-cycle" class="nav-link" data-scroll-target="#ai-supported-knowledge-construction-cycle">3.2 AI-Supported Knowledge Construction Cycle</a></li>
  <li><a href="#prompt-before-provide" id="toc-prompt-before-provide" class="nav-link" data-scroll-target="#prompt-before-provide">3.3 Prompt Before Provide</a></li>
  <li><a href="#core-ai-companion-functions" id="toc-core-ai-companion-functions" class="nav-link" data-scroll-target="#core-ai-companion-functions">3.4 Core AI Companion Functions</a></li>
  <li><a href="#conceptual-system-architecture" id="toc-conceptual-system-architecture" class="nav-link" data-scroll-target="#conceptual-system-architecture">3.5 Conceptual System Architecture</a></li>
  <li><a href="#prototype-implementation" id="toc-prototype-implementation" class="nav-link" data-scroll-target="#prototype-implementation">3.6 Prototype Implementation</a></li>
  </ul></li>
  <li><a href="#formative-evaluation" id="toc-formative-evaluation" class="nav-link" data-scroll-target="#formative-evaluation">4. Formative Evaluation</a>
  <ul class="collapse">
  <li><a href="#evaluation-purpose" id="toc-evaluation-purpose" class="nav-link" data-scroll-target="#evaluation-purpose">4.1 Evaluation Purpose</a></li>
  <li><a href="#participants-and-learning-context" id="toc-participants-and-learning-context" class="nav-link" data-scroll-target="#participants-and-learning-context">4.2 Participants and Learning Context</a></li>
  <li><a href="#procedure" id="toc-procedure" class="nav-link" data-scroll-target="#procedure">4.3 Procedure</a></li>
  <li><a href="#evaluation-constructs-and-measures" id="toc-evaluation-constructs-and-measures" class="nav-link" data-scroll-target="#evaluation-constructs-and-measures">4.4 Evaluation Constructs and Measures</a></li>
  <li><a href="#human-ai-interaction-analysis" id="toc-human-ai-interaction-analysis" class="nav-link" data-scroll-target="#human-ai-interaction-analysis">4.5 Human-AI Interaction Analysis</a></li>
  <li><a href="#pilot-study-results" id="toc-pilot-study-results" class="nav-link" data-scroll-target="#pilot-study-results">4.6 Pilot Study Results</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">5. Discussion</a>
  <ul class="collapse">
  <li><a href="#reframing-the-role-of-generative-ai-in-learning" id="toc-reframing-the-role-of-generative-ai-in-learning" class="nav-link" data-scroll-target="#reframing-the-role-of-generative-ai-in-learning">5.1 Reframing the Role of Generative AI in Learning</a></li>
  <li><a href="#personal-knowledge-as-an-evolving-artefact" id="toc-personal-knowledge-as-an-evolving-artefact" class="nav-link" data-scroll-target="#personal-knowledge-as-an-evolving-artefact">5.2 Personal Knowledge as an Evolving Artefact</a></li>
  <li><a href="#implications-for-hci-and-aied-design" id="toc-implications-for-hci-and-aied-design" class="nav-link" data-scroll-target="#implications-for-hci-and-aied-design">5.3 Implications for HCI and AIED Design</a></li>
  </ul></li>
  <li><a href="#limitations-and-future-research" id="toc-limitations-and-future-research" class="nav-link" data-scroll-target="#limitations-and-future-research">6. Limitations and Future Research</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">7. Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">📚 References</a>
  <ul class="collapse">
  <li><a href="#writing-to-learn-and-knowledge-construction" id="toc-writing-to-learn-and-knowledge-construction" class="nav-link" data-scroll-target="#writing-to-learn-and-knowledge-construction">Writing-to-Learn and Knowledge Construction</a></li>
  <li><a href="#metacognition-and-self-regulated-learning-1" id="toc-metacognition-and-self-regulated-learning-1" class="nav-link" data-scroll-target="#metacognition-and-self-regulated-learning-1">Metacognition and Self-Regulated Learning</a></li>
  <li><a href="#personal-knowledge-management-and-digital-gardens" id="toc-personal-knowledge-management-and-digital-gardens" class="nav-link" data-scroll-target="#personal-knowledge-management-and-digital-gardens">Personal Knowledge Management and Digital Gardens</a></li>
  <li><a href="#generative-ai-in-education-and-cognitive-offloading" id="toc-generative-ai-in-education-and-cognitive-offloading" class="nav-link" data-scroll-target="#generative-ai-in-education-and-cognitive-offloading">Generative AI in Education and Cognitive Offloading</a></li>
  <li><a href="#epistemic-agency-and-learner-in-the-loop" id="toc-epistemic-agency-and-learner-in-the-loop" class="nav-link" data-scroll-target="#epistemic-agency-and-learner-in-the-loop">Epistemic Agency and Learner-in-the-Loop</a></li>
  <li><a href="#socratic-tutoring-and-intelligent-systems" id="toc-socratic-tutoring-and-intelligent-systems" class="nav-link" data-scroll-target="#socratic-tutoring-and-intelligent-systems">Socratic Tutoring and Intelligent Systems</a></li>
  </ul></li>
  <li><a href="#related-work-and-systems" id="toc-related-work-and-systems" class="nav-link" data-scroll-target="#related-work-and-systems">🔗 Related Work and Systems</a>
  <ul class="collapse">
  <li><a href="#intelligent-tutoring-systems" id="toc-intelligent-tutoring-systems" class="nav-link" data-scroll-target="#intelligent-tutoring-systems">Intelligent Tutoring Systems</a></li>
  <li><a href="#personal-knowledge-management-systems" id="toc-personal-knowledge-management-systems" class="nav-link" data-scroll-target="#personal-knowledge-management-systems">Personal Knowledge Management Systems</a></li>
  <li><a href="#digital-gardens-and-networked-thought" id="toc-digital-gardens-and-networked-thought" class="nav-link" data-scroll-target="#digital-gardens-and-networked-thought">Digital Gardens and Networked Thought</a></li>
  <li><a href="#ai-scaffolding-systems" id="toc-ai-scaffolding-systems" class="nav-link" data-scroll-target="#ai-scaffolding-systems">AI Scaffolding Systems</a></li>
  </ul></li>
  <li><a href="#connections-to-ai-research-tracker" id="toc-connections-to-ai-research-tracker" class="nav-link" data-scroll-target="#connections-to-ai-research-tracker">🔗 Connections to AI Research Tracker</a></li>
  <li><a href="#notes-for-implementation" id="toc-notes-for-implementation" class="nav-link" data-scroll-target="#notes-for-implementation">📝 Notes for Implementation</a>
  <ul class="collapse">
  <li><a href="#current-implementation-status" id="toc-current-implementation-status" class="nav-link" data-scroll-target="#current-implementation-status">Current Implementation Status</a></li>
  </ul></li>
  <li><a href="#citation" id="toc-citation" class="nav-link" data-scroll-target="#citation">📊 Citation</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">From Notes to Knowledge: Designing an AI Wiki Companion for Learner-in-the-Loop Knowledge Construction</h1>
  <div class="quarto-categories">
    <div class="quarto-category">AI in Education</div>
    <div class="quarto-category">Knowledge Construction</div>
    <div class="quarto-category">Human-AI Interaction</div>
    <div class="quarto-category">Personal Knowledge Management</div>
    <div class="quarto-category">Metacognition</div>
  </div>
  </div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Research Team </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            AI Education Research
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 2, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>Generative artificial intelligence (GenAI) has substantially reduced the effort required to produce summaries, explanations, structured notes, and other learning artefacts. Although such capabilities can increase access to information and provide timely instructional support, they also introduce a pedagogical tension: the same cognitive activities that GenAI can efficiently automate, including explaining, organising, connecting, and reformulating information, may themselves constitute important processes through which learning occurs. This paper proposes an AI Wiki Companion, a learner-in-the-loop personal knowledge environment designed to position GenAI as a metacognitive and formative scaffold rather than as a substitute knowledge producer. Drawing on writing-to-learn, knowledge construction, metacognition, self-regulated learning, personal knowledge management, and human-in-the-loop perspectives, the framework treats learner-authored wiki entries as evolving external representations of understanding. Four design principles guide the proposed system: DP1 Learner Ownership, DP2 Scaffold Rather Than Substitute, DP3 Reflection Before Correction, and DP4 Continuous Knowledge Integration. These principles are operationalised through a five-stage cycle comprising Construct → Reflect → Scaffold → Consolidate &amp; Apply → Revisit &amp; Extend. A complementary Prompt Before Provide interaction model encourages learners to articulate and evaluate their existing understanding before receiving direct AI-generated explanations. We present a functional prototype implementing the complete five-stage cycle and report findings from a pilot study (N=7) demonstrating that the framework successfully preserves epistemic agency (M=4.36/5.0), supports iterative knowledge revision (M=2.9 revisions per concept), and promotes active engagement over passive consumption. The proposed approach contributes a design perspective for educational GenAI in which technological assistance is deliberately organised to preserve rather than displace the cognitive activities that constitute learning.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>generative artificial intelligence, knowledge construction, learner-in-the-loop, writing-to-learn, metacognition, self-regulated learning, personal wiki, cognitive offloading, AI in education</p>
  </div>
</div>

</header>


<section id="conference-paper" class="level2 conference-paper-header">
<h2 class="anchored" data-anchor-id="conference-paper">📄 Conference Paper</h2>
<p><strong>Title:</strong> From Notes to Knowledge: Designing an AI Wiki Companion for Learner-in-the-Loop Knowledge Construction</p>
<p><strong>Status:</strong> Draft (To Be Submitted)</p>
<p><strong>Date:</strong> September 2, 2026</p>
<p><strong>Categories:</strong> AI in Education, Knowledge Construction, Human-AI Interaction, Personal Knowledge Management, Metacognition</p>
</section>
<hr>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<section id="from-information-access-to-knowledge-construction" class="level3">
<h3 class="anchored" data-anchor-id="from-information-access-to-knowledge-construction">1.1 From Information Access to Knowledge Construction</h3>
<p>Generative artificial intelligence has transformed the conditions under which learners locate, organise, and interact with information. Contemporary large language models can rapidly summarise readings, explain unfamiliar concepts, generate examples, compare theoretical perspectives, formulate questions, and produce coherent notes. From an accessibility and efficiency perspective, these capabilities provide considerable educational value. They can reduce barriers to information access, provide immediate assistance, and potentially extend learning support beyond the temporal and practical constraints of conventional teaching environments.</p>
<p>Yet empirical research has begun to reveal a concerning pattern. Chen et al.&nbsp;(2025), in a systematic review of 67 studies on ChatGPT in higher education (2022-2025), found that while students using AI tools showed improved task completion, they demonstrated reduced performance on unassisted transfer tasks. Kim and Lee (2026) documented what they term the “performance paradox”: short-term task performance improves with AI assistance, while durable long-term learning may be compromised. These findings point to a critical distinction: access to well-organised information does not necessarily imply that knowledge has been meaningfully constructed by the learner.</p>
<p>Research on active and constructive learning has consistently distinguished between receiving information and engaging cognitively with that information. Meaningful understanding requires learners to select relevant information, organise conceptual representations, integrate new ideas with prior knowledge, identify relationships, evaluate competing explanations, retrieve knowledge from memory, and apply that knowledge in unfamiliar circumstances. Writing has traditionally provided one mechanism through which some of these processes become visible. When learners explain a concept in their own words, they externalise aspects of their current mental model. The resulting artefact can expose conceptual gaps, uncertain relationships, and misconceptions that may remain concealed when information is merely read or copied.</p>
<p>Nevertheless, digital note-taking practices do not inherently produce such constructive engagement. Notes may become repositories into which information is copied, stored, and rarely reconsidered. A simplified representation of this behaviour is <strong>Read → Copy → Store → Rarely Revisit</strong>. GenAI potentially introduces an even more efficient version of the same problem: <strong>Ask AI → Generate Summary → Save Summary</strong>. In the latter workflow, a polished and apparently coherent knowledge artefact may be produced with relatively little requirement for the learner to decide what is important, formulate an explanation, identify conceptual relationships, or evaluate the validity of the resulting text.</p>
<p>The issue is not that AI-generated summaries or explanations are intrinsically educationally undesirable. Rather, the concern is one of <strong>cognitive substitution</strong>. Cognitive offloading can be beneficial when external tools release limited cognitive resources for more demanding tasks, but it can become pedagogically problematic when the process being offloaded is itself an intended object of learning (Sparrow et al., 2011; Sweller, 1988). A learner who delegates conceptual organisation, explanation, and synthesis to an AI system may obtain a high-quality artefact without necessarily engaging in the corresponding cognitive activity.</p>
<p>This tension motivates the central question addressed by the present work:</p>
<blockquote class="blockquote">
<p><strong>How can generative AI support knowledge construction without performing the knowledge-construction process for the learner?</strong></p>
</blockquote>
<p>The paper argues that educational GenAI should not be evaluated only according to what it can generate for learners. An equally important design question concerns which forms of intellectual activity should deliberately remain under learner control because performing those activities contributes to learning.</p>
</section>
<section id="personal-wikis-as-environments-for-developing-knowledge" class="level3">
<h3 class="anchored" data-anchor-id="personal-wikis-as-environments-for-developing-knowledge">1.2 Personal Wikis as Environments for Developing Knowledge</h3>
<p>The proposed approach addresses this problem through a personal wiki environment. Unlike conventional linear notes, a personal wiki can represent knowledge as an evolving network of learner-generated concepts. Individual entries can be revised, linked, reorganised, and extended as understanding develops. Hyperlinks, backlinks, tags, revision histories, and graphical representations of conceptual relationships allow knowledge to be treated as interconnected rather than as a sequence of isolated documents.</p>
<p>This characteristic is educationally significant because learning frequently requires new information to be interpreted in relation to existing knowledge. The value of a personal wiki therefore lies not simply in external storage. It can function as an evolving external representation of the learner’s current knowledge structure. A learner studying machine learning, for example, might initially create separate entries for overfitting, generalisation, and model evaluation. Later encounters with regularisation or cross-validation can provide occasions to revise earlier explanations and construct new relationships among these concepts.</p>
<p>The present work draws inspiration from linked-note and personal knowledge management environments such as Obsidian, particularly their use of persistent Markdown documents, hyperlinks, backlinks, tags, and concept graphs. However, the contribution extends beyond existing PKM systems augmented with AI chat interfaces. While tools like Khanmigo and Quizlet AI provide guided tutoring or personalised study assistance, they do not treat the learner’s persistent knowledge artefacts as the primary context for scaffolding. The personal wiki is conceptualised more generally as an HCI environment in which learner-generated representations of knowledge persist over time and provide contextual material for subsequent AI-supported reflection. This longitudinal orientation distinguishes the proposed approach from conversational AI interactions that primarily respond to the immediate prompt without reference to the learner’s evolving knowledge base.</p>
</section>
<section id="from-ai-content-generation-to-ai-supported-knowledge-construction" class="level3">
<h3 class="anchored" data-anchor-id="from-ai-content-generation-to-ai-supported-knowledge-construction">1.3 From AI Content Generation to AI-Supported Knowledge Construction</h3>
<p>The AI Wiki Companion proposed in this paper adopts a deliberately constrained pedagogical role for GenAI. Rather than treating AI primarily as an answer generator or automatic note writer, the system positions it as a source of metacognitive prompts, Socratic questioning, formative feedback, knowledge-gap identification, conceptual challenges, and connection recommendations. The purpose of AI intervention is consequently not always to minimise the effort required to complete a task. In some interactions, the system deliberately returns intellectual work to the learner.</p>
<p>The core principle can be expressed as follows:</p>
<blockquote class="blockquote">
<p><strong>The learner constructs the knowledge; AI scaffolds the construction process.</strong></p>
</blockquote>
<p>This principle establishes a division of epistemic responsibility between learner and system. The AI may identify a potentially missing connection, question the coherence of an explanation, or recommend that an earlier wiki entry be reconsidered. The learner nevertheless retains responsibility for determining whether the suggestion is valid, whether the knowledge artefact should be changed, and how that change should be expressed. Such an arrangement extends human-in-the-loop thinking into a specifically educational form of <strong>learner-in-the-loop knowledge construction</strong>, in which the learner retains epistemic agency over the representation and revision of personal knowledge.</p>
<p>This paper makes three distinct theoretical contributions:</p>
<ol type="1">
<li><p><strong>A Learner-in-the-Loop Knowledge Construction Framework:</strong> We extend human-in-the-loop concepts from software engineering to educational theory, specifying how epistemic agency can be preserved in AI-supported learning. This framework integrates writing-to-learn, self-regulated learning, and personal knowledge management perspectives into a unified model.</p></li>
<li><p><strong>Operational Design Principles and Interaction Model:</strong> We translate theoretical principles into four concrete design principles (Learner Ownership, Scaffold Rather Than Substitute, Reflection Before Correction, Continuous Knowledge Integration) and a five-stage knowledge-construction cycle, together with the Prompt Before Provide interaction mechanism that structures learner-AI engagement.</p></li>
<li><p><strong>A Formative Evaluation Approach:</strong> We propose an architecture and methodological framework for empirically examining the relationship between AI scaffolding, learner decision-making, knowledge-artefact revision, and conceptual understanding, enabling systematic investigation of learner-in-the-loop mechanisms.</p></li>
</ol>
<p>These contributions advance the field by moving beyond questions of AI capability to address how AI systems can be designed to support, rather than supplant, the cognitive processes that constitute learning.</p>
</section>
<section id="research-questions" class="level3">
<h3 class="anchored" data-anchor-id="research-questions">1.4 Research Questions</h3>
<p>The study is guided by the following research questions:</p>
<p><strong>RQ1. Design:</strong> How can a learner-in-the-loop AI wiki be designed to support active knowledge construction while maintaining learner agency?<br>
<em>RQ1 examines how the theoretical principles of learner ownership, scaffolding, reflection, and continuous knowledge integration can be operationalised through the design of the AI Wiki Companion.</em></p>
<p><strong>RQ2. Learning:</strong> To what extent does the proposed AI Wiki Companion support students’ knowledge construction and conceptual understanding?<br>
<em>RQ2 investigates whether engagement with the proposed environment is associated with changes in conceptual understanding and the quality of learner-generated knowledge artefacts, measured through pre-post assessments and artefact analysis.</em></p>
<p><strong>RQ3. Human-AI Interaction:</strong> How do learners evaluate and act upon AI-generated scaffolding during the construction and revision of their personal knowledge artefacts?<br>
<em>RQ3 focuses on the learner-in-the-loop mechanism itself. It examines how learners respond to AI-generated questions, challenges, gap identifications, and connection recommendations, including whether suggestions are accepted, rejected, modified, or independently resolved.</em></p>
<p><strong>RQ4. Learner Experience:</strong> How do students perceive the usefulness of AI-supported reflection, feedback, and knowledge linking during wiki-based learning?<br>
<em>RQ4 examines learners’ perceptions of the AI Wiki Companion, including perceived usefulness, learner control, reflective support, cognitive engagement, and potential dependency on AI.</em></p>
<p>Together, the four questions provide a progression from <strong>design → learning → interaction → experience</strong>, enabling the proposed system to be evaluated not only in terms of whether it supports learning, but also in terms of how AI scaffolding influences learner activity and how that support is experienced. This multi-faceted approach aligns with calls for comprehensive evaluation frameworks in AI education research that examine both learning outcomes and the mechanisms through which they are achieved (Luckin et al., 2023; Zawacki-Richter et al., 2019).</p>
<hr>
</section>
</section>
<section id="theoretical-background-and-related-work" class="level2">
<h2 class="anchored" data-anchor-id="theoretical-background-and-related-work">2. Theoretical Background and Related Work</h2>
<p>The AI Wiki Companion draws on three interconnected theoretical traditions: (1) writing-to-learn and knowledge construction, which establish the cognitive value of learner-authored explanations; (2) metacognition and self-regulated learning, which provide frameworks for understanding how learners monitor and adapt their understanding; and (3) personal knowledge management and human-AI interaction, which inform the design of environments that support persistent, networked knowledge representation while preserving learner agency.</p>
<p>This section synthesises these perspectives to establish the theoretical foundation for the proposed learner-in-the-loop framework. We begin with writing-to-learn research, which demonstrates that the act of constructing explanations itself promotes deeper cognitive processing. We then examine metacognition and self-regulated learning frameworks, which explain how learners can be scaffolded to monitor and adapt their understanding. Next, we review personal knowledge management and digital gardens, which provide the environmental context for persistent knowledge construction. We then consider generative AI in education, examining both its affordances and the risks of cognitive offloading. Finally, we synthesise these perspectives to identify the research gap that the AI Wiki Companion addresses: the lack of AI systems explicitly designed around preserving epistemic agency while supporting longitudinal knowledge construction.</p>
<section id="writing-to-learn-and-active-knowledge-construction" class="level3">
<h3 class="anchored" data-anchor-id="writing-to-learn-and-active-knowledge-construction">2.1 Writing-to-Learn and Active Knowledge Construction</h3>
<p>The theoretical foundation of the proposed approach begins with the proposition that writing can function as a cognitive activity rather than merely as a means of recording completed thought. Writing-to-learn research has examined how the production of explanations, summaries, learning journals, and other written artefacts can require learners to select information, organise ideas, establish conceptual relationships, and make implicit understanding explicit.</p>
<p>Seminal meta-analyses have established the efficacy of writing-to-learn interventions. Fiorella and Mayer (2015) identified eight generative learning strategies, including summarising, mapping, and self-explaining, that promote deeper cognitive processing when learners actively construct mental representations. Their work demonstrates that learning gains depend not on writing per se, but on whether writing tasks engage learners in selection, organisation, and integration of information. Graham et al.&nbsp;(2020) conducted a comprehensive meta-analysis of 56 experiments examining writing in science, social studies, and mathematics, finding moderate to large positive effects on content learning (g = 0.49 to 0.76). These effects were strongest when writing tasks required elaboration and conceptual organisation rather than simple transcription.</p>
<p>From a knowledge-construction perspective, this externalisation process is important because it creates an inspectable representation of the learner’s current understanding. A concept that appears familiar while being read may prove more difficult to explain independently. Similarly, attempting to connect two ideas in writing may expose ambiguity about their underlying relationship. The production of a learner-authored wiki entry can therefore operate as an epistemic activity through which understanding is articulated, tested, and progressively reorganised (Bereiter and Scardamalia, 1987).</p>
<p>However, writing alone should not be assumed to guarantee meaningful learning. The educational effect depends on the nature of the writing activity and on whether learners engage in cognitively productive processes such as elaboration, organisation, monitoring, and revision (Biswas-Vaughan and Kaish, 2019). This observation is particularly relevant to the design of AI-supported learning. If GenAI produces the explanation before the learner has attempted to formulate one, the visible written artefact may no longer provide reliable evidence of the learner’s own conceptual representation.</p>
<p>Consequently, the proposed AI Wiki Companion gives priority to <strong>learner-generated initial representations</strong>. AI support is introduced around and after the learner’s constructive activity rather than automatically preceding it.</p>
</section>
<section id="metacognition-and-self-regulated-learning" class="level3">
<h3 class="anchored" data-anchor-id="metacognition-and-self-regulated-learning">2.2 Metacognition and Self-Regulated Learning</h3>
<p>Knowledge construction also depends on learners’ ability to monitor and regulate their own understanding. Metacognition encompasses awareness of one’s cognitive state as well as processes through which learners evaluate comprehension, recognise uncertainty, select strategies, and determine when further learning is required. These functions are closely associated with self-regulated learning (SRL), within which learners iteratively plan, perform, monitor, and adapt learning activity.</p>
<p>Zimmerman’s (2000) cyclical model of SRL provides a comprehensive framework for understanding these processes across three phases: forethought (goal setting, strategic planning), performance (self-control, self-observation), and self-reflection (self-evaluation, causal attribution). This model has been extensively validated across domains and is widely used to design scaffolding interventions (Panadero, 2017). Winne and Hadwin’s (1998) recursive processing framework similarly emphasises how learners construct task representations, set goals, execute strategies, and adapt based on feedback, with metacognitive monitoring operating at each stage.</p>
<p>A learner may possess an incomplete explanation without recognising that it is incomplete. Effective scaffolding therefore requires more than correction. It should encourage the learner to detect and interpret the discrepancy between present understanding and a more adequate conceptual representation. Questions such as <em>“Which part of this explanation are you least confident about?”</em>, <em>“What evidence supports this statement?”</em>, or <em>“Can you explain this concept without referring to your note?”</em> can stimulate metacognitive monitoring without immediately supplying the missing content (Azevedo and Hadwin, 2005).</p>
<p>GenAI is potentially well suited to this form of context-sensitive prompting because prompts can be generated in relation to the learner’s current artefact rather than delivered as generic reflective questions. Nevertheless, the educational quality of such support depends on interaction design. An AI system that detects a weakness and immediately rewrites the corresponding paragraph may resolve the textual problem while bypassing the learner’s opportunity to monitor and regulate understanding. The proposed framework therefore emphasises <strong>reflection before correction</strong>, treating AI feedback as a prompt for learner regulation rather than as an automatic repair mechanism.</p>
<p>This perspective also resonates with scaffolding within sociocultural accounts of learning, in which assistance is most productive when it enables learners to perform cognitive activity that would otherwise be difficult while progressively preserving or increasing learner responsibility (Wood, Bruner and Ross, 1976). The analogy should not be interpreted as equating an LLM with a human teacher or more knowledgeable other. Rather, it provides a theoretical lens for considering how adaptive prompts might support productive learner activity without eliminating that activity.</p>
</section>
<section id="personal-wikis-and-networked-knowledge-environments" class="level3">
<h3 class="anchored" data-anchor-id="personal-wikis-and-networked-knowledge-environments">2.3 Personal Wikis and Networked Knowledge Environments</h3>
<p>The metacognitive processes described above operate within an environmental context. Personal knowledge management systems provide that context by offering persistent, interconnected representations of knowledge that can evolve over time.</p>
<p>Personal knowledge management systems provide an external environment in which learners can store, organise, link, and revisit information over extended periods. Whereas conventional notes are often structured around lectures, documents, or chronological sequences, wiki-style environments allow individual concepts to become persistent entities that can be connected across contexts.</p>
<p>Recent research on digital gardens and networked note-taking has examined how these environments support knowledge construction over time. Appleton (2020) defines digital gardening as a practice of cultivating notes as evolving, interconnected artefacts rather than static publications, emphasising the iterative nature of knowledge development. Reck (2023) provides evidence-based guidance for academic PKM systems, highlighting the importance of consistent capture routines and tool interoperability for sustaining long-term knowledge work.</p>
<p>From an educational perspective, this persistence supports an important shift from <strong>note accumulation to knowledge evolution</strong>. A learner may initially represent concepts as isolated entries but progressively develop a more relational structure as understanding grows. Backlinks and concept graphs can make these relationships visible, while revision histories provide evidence of how conceptual representations change over time (Fathizargan, 2017).</p>
<p>Such environments may therefore support the externalisation of mental models. A knowledge graph displayed by the system should not be interpreted as a direct representation of cognition, but it can reveal aspects of how a learner has chosen to organise and connect concepts. These external representations can subsequently become objects for reflection and discussion (Suthers, 2001).</p>
<p>The AI Wiki Companion extends this affordance by using the learner’s existing knowledge base as part of the context for AI intervention. Rather than responding only to the current page, the system can identify potentially relevant prior entries and encourage the learner to consider whether new knowledge modifies, contradicts, or extends earlier understanding. This longitudinal orientation distinguishes the proposed approach from many conversational AI interactions that primarily respond to the immediate prompt.</p>
</section>
<section id="generative-ai-as-formative-and-metacognitive-scaffolding" class="level3">
<h3 class="anchored" data-anchor-id="generative-ai-as-formative-and-metacognitive-scaffolding">2.4 Generative AI as Formative and Metacognitive Scaffolding</h3>
<p>The environmental affordances of personal wikis become pedagogically significant when combined with AI support. GenAI applications in education have frequently been investigated as tutors, writing assistants, content generators, assessment aids, and feedback systems. These applications demonstrate several potentially valuable affordances, including responsiveness, scalability, conversational interaction, and the ability to generate personalised explanations or feedback (Roll and Wylie, 2016). At the same time, concerns have been raised regarding hallucination, automation bias, over-reliance, inaccurate feedback, and the possibility that students may outsource reasoning or writing processes to AI (Zawacki-Richter et al., 2019).</p>
<p>The distinction between <strong>formative scaffolding and content substitution</strong> is therefore central to the proposed design. Consider a learner who writes that increasing model complexity necessarily increases model performance. An AI system operating as an automatic editor might replace this statement with a more technically accurate explanation. A scaffolding-oriented system could instead ask: <em>“Does increasing model complexity always improve performance on unseen data? Under what conditions might the opposite occur?”</em> The second response leaves the epistemic problem unresolved long enough for the learner to engage with it.</p>
<p>This design logic is related to Socratic tutoring approaches, in which questioning is used to stimulate explanation, justification, comparison, and reconsideration rather than immediately providing conclusions. VanLehn’s (2011) meta-analysis of intelligent tutoring systems found that well-designed ITS produced learning gains approximately equivalent to one-on-one human tutoring, with Socratic-style questioning identified as a key mechanism. Recent work has extended these principles to LLM-based tutors; for example, the Socratic Chatbot proposed by Chen et al.&nbsp;(2024) encourages self-reflection through structured questioning rather than direct answers, showing promise in enhancing critical thinking skills.</p>
<p>Recent empirical research provides compelling evidence for the efficacy of AI tutoring systems. Lo et al.&nbsp;(2025) conducted a randomised controlled trial demonstrating that LLM-based tutors outperformed in-class active learning in K-12 mathematics, with effect sizes suggesting substantial learning gains. Similarly, Xu et al.&nbsp;(2026) conducted a decade-long meta-analysis of 35 empirical studies (2013-2025) examining AI support for self-regulated learning, finding that well-designed AI scaffolds significantly improved SRL processes and learning outcomes when aligned with Zimmerman’s cyclical model.</p>
<p>However, GenAI introduces both opportunities and risks. Its flexibility permits questions to be generated dynamically from learner-authored material, but the quality and factual reliability of those prompts cannot be assumed. Human judgement, source verification, and appropriate system guardrails therefore remain necessary (Luckin et al., 2023). Recent systematic reviews have synthesised 67 empirical studies on ChatGPT’s cognitive impact in higher education (2022-2025), revealing both potential benefits for critical thinking and significant concerns regarding over-reliance and diminished effortful reasoning (Chen et al., 2025).</p>
</section>
<section id="learner-in-the-loop-knowledge-construction" class="level3">
<h3 class="anchored" data-anchor-id="learner-in-the-loop-knowledge-construction">2.5 Learner-in-the-Loop Knowledge Construction</h3>
<p>The scaffolding approaches described above presuppose that the learner retains agency over knowledge construction. Without such agency, AI support risks becoming cognitive substitution rather than scaffolding.</p>
<p>Human-in-the-loop approaches are generally concerned with retaining meaningful human oversight within computational decision processes. For educational contexts, a more specific concern is whether the learner continues to exercise <strong>epistemic agency</strong>: the capacity to formulate, evaluate, justify, and revise claims about what is known.</p>
<p>Recent research on GenAI and epistemic agency has emphasised the importance of preserving learner control over knowledge construction. Wu et al.&nbsp;(2025) argue that strengthening human epistemic agency in symbiotic learning partnerships requires proper instructional scaffolds and learner reflection, noting that GenAI alone may not directly alter learners’ epistemic stances but can contribute to gradual evolution when combined with metacognitive support. Similarly, the concept of “epistemic co-agency” proposed by Lee and Yuan (2026) frames AI as a provocative companion that can catalyse deeper thinking when deliberately scaffolded, rather than as an authoritative knowledge source.</p>
<p>Emerging research has begun to operationalise and measure learner agency in AI-assisted contexts. Dai et al.&nbsp;(2026) proposed a framework for redefining and measuring student agency in AI-assisted learning, identifying key dimensions including autonomy in tool selection, control over AI outputs, and capacity for critical evaluation. Their findings suggest that agency is not uniformly enhanced by AI tools but depends critically on interaction design and pedagogical scaffolding.</p>
<p>The proposed learner-in-the-loop model treats AI output as provisional input to learner judgement. A suggestion does not directly become part of the personal knowledge base. Instead, the interaction follows a conceptual sequence of <strong>Construct → Judge Feedback → Revise Ideas → Accept / Reject AI → Apply Knowledge</strong>. In this sequence, AI may influence the learner’s reasoning, but the learner remains responsible for deciding whether and how an artefact is revised.</p>
<p>This distinction becomes particularly important when AI-generated information is plausible but incorrect. A system that automatically integrates AI-generated content into a student’s wiki could amplify errors and weaken the relationship between the artefact and the learner’s own understanding. Requiring explicit learner evaluation introduces cognitive friction, but such friction may be educationally productive when it encourages verification and justification (Darvishi et al., 2024).</p>
<p>The learner-in-the-loop concept therefore functions simultaneously as a pedagogical principle and an HCI design constraint. It requires interaction mechanisms that make AI intervention visible, contestable, and reversible, while preventing suggestions from being silently incorporated into learner-authored knowledge.</p>
</section>
<section id="cognitive-offloading-and-the-risk-of-substitution" class="level3">
<h3 class="anchored" data-anchor-id="cognitive-offloading-and-the-risk-of-substitution">2.6 Cognitive Offloading and the Risk of Substitution</h3>
<p>Cognitive offloading refers to the use of physical or digital actions to reduce mental demand. While offloading can be beneficial when it releases cognitive resources for higher-order tasks, it becomes problematic when the offloaded process is itself the intended object of learning (Kahneman, 2011; Sweller, 1988).</p>
<p>Recent research on AI and cognitive offloading has raised concerns about the “performance paradox”: students’ short-term task performance improves with AI assistance, while durable long-term learning may be compromised (Kim and Lee, 2026). The fluency of AI-generated output can create an illusion of competence and encourage metacognitive laziness, leading learners to abdicate the generative effort required to build deep knowledge (Inan et al., 2026). Grinschgl and Neubauer (2022) similarly warn that unstructured AI use trends toward detrimental offloading, creating risks of cognitive atrophy when learners consistently outsource core thinking processes.</p>
<p>Recent empirical studies have documented these concerns across multiple domains. Zhang et al.&nbsp;(2026) examined cognition, agency, and epistemic development in AI-assisted learning, finding that cognitive offloading reduces opportunities for effortful reasoning and contributes to illusory learning and overtrust. Chen et al.&nbsp;(2025), in their systematic review of 67 studies, identified a consistent pattern where students using AI tools showed improved task completion but reduced performance on unassisted transfer tasks, suggesting diminished durable learning.</p>
<p>However, cognitive offloading is not inherently undesirable. The critical distinction lies between <strong>beneficial offloading</strong> (releasing resources for more demanding cognition) and <strong>maladaptive offloading</strong> (bypassing learning-relevant processes) (Sparrow et al., 2011). The AI Wiki Companion addresses this tension by deliberately preserving learner engagement with knowledge-construction activities while using AI to scaffold reflection, identify gaps, and recommend connections.</p>
</section>
<section id="research-gap-and-theoretical-contribution" class="level3">
<h3 class="anchored" data-anchor-id="research-gap-and-theoretical-contribution">2.7 Research Gap and Theoretical Contribution</h3>
<p>Taken together, writing-to-learn, metacognitive regulation, personal knowledge environments, and AI-supported feedback provide important theoretical components for the proposed approach. However, these areas are frequently treated separately. Writing-to-learn research typically focuses on the cognitive consequences of producing written explanations; personal knowledge management research examines external organisation and retrieval; and GenAI research increasingly investigates immediate feedback, tutoring, or content generation.</p>
<p>Comparatively less attention has been directed towards GenAI systems explicitly designed around <strong>persistent learner-generated knowledge artefacts</strong> and the longitudinal processes through which those artefacts are constructed, questioned, connected, revised, retrieved, and applied.</p>
<p>The research gap is therefore not simply an absence of AI-supported note-taking systems. The more specific gap concerns the design of AI support that deliberately preserves the learner’s role as the primary constructor and evaluator of knowledge while using generative capabilities to stimulate productive cognitive and metacognitive activity.</p>
<p><strong>Current approaches fall into two categories:</strong></p>
<ol type="1">
<li><p><strong>Content-generation mode:</strong> AI produces explanations, summaries, or notes that learners consume or lightly edit (e.g., automatic summarisation tools, AI writing assistants). This approach risks cognitive offloading without ensuring constructive engagement.</p></li>
<li><p><strong>Generic tutoring mode:</strong> AI provides conversational tutoring or Q&amp;A support that is not anchored in the learner’s persistent knowledge artefacts (e.g., standalone chatbots, Khanmigo-style tutors). This approach may support learning but does not leverage the longitudinal knowledge base as a context for scaffolding.</p></li>
</ol>
<p><strong>Comparative positioning:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 19%">
<col style="width: 26%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Approach</th>
<th>Learner Agency</th>
<th>Longitudinal Context</th>
<th>Scaffolding Type</th>
<th>Primary Risk</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>AI Note Generators</strong></td>
<td>Low</td>
<td>No</td>
<td>Content substitution</td>
<td>Cognitive offloading</td>
</tr>
<tr class="even">
<td><strong>Chatbot Tutors</strong></td>
<td>Medium</td>
<td>No</td>
<td>Episodic Q&amp;A</td>
<td>Disconnected learning</td>
</tr>
<tr class="odd">
<td><strong>AI Wiki Companion</strong></td>
<td><strong>High</strong></td>
<td><strong>Yes</strong></td>
<td><strong>Contextual scaffolding</strong></td>
<td><strong>Mitigated by design</strong></td>
</tr>
</tbody>
</table>
<p><strong>Theoretical contribution:</strong> The AI Wiki Companion addresses this gap through the <strong>learner-in-the-loop knowledge construction framework</strong>, which extends human-in-the-loop concepts from software engineering to educational theory. This framework specifies how epistemic agency can be preserved through four design principles (Learner Ownership, Scaffold Rather Than Substitute, Reflection Before Correction, Continuous Knowledge Integration) and operationalised through a five-stage knowledge-construction cycle. The framework integrates writing-to-learn, SRL, and PKM perspectives into a unified model for AI-supported learning that treats the learner’s persistent knowledge artefacts as the primary context for scaffolding.</p>
<p>This contribution advances the field by: 1. <strong>Theoretical extension:</strong> Adapting human-in-the-loop from software engineering to educational theory with explicit focus on epistemic agency 2. <strong>Design specification:</strong> Providing concrete, operationalisable principles rather than abstract guidelines 3. <strong>Integration:</strong> Unifying three theoretical traditions (writing-to-learn, SRL, PKM) into a coherent framework 4. <strong>Practical guidance:</strong> Offering implementable mechanisms (Prompt Before Provide, 5-stage cycle) for system designers</p>
<p>The AI Wiki Companion addresses this gap through four design principles and an iterative five-stage model of AI-supported knowledge construction.</p>
<p><strong>Figure 1. Learner-in-the-Loop Knowledge Construction Framework</strong></p>
<pre><code>┌─────────────────────────────────────────────────────────────────────────────┐
│                    THEORETICAL FOUNDATIONS                                  │
├─────────────────────────────────────────────────────────────────────────────┤
│  Writing-to-Learn        Metacognition &amp; SRL      Personal Knowledge Mgmt  │
│  • Externalisation       • Self-monitoring        • Persistent artefacts   │
│  • Generative process    • Self-regulation        • Networked concepts     │
│  • Explanation quality   • Calibration            • Revision history       │
└─────────────────────────────────────────────────────────────────────────────┘
                                    ↓
┌─────────────────────────────────────────────────────────────────────────────┐
│                    DESIGN PRINCIPLES                                        │
├─────────────────────────────────────────────────────────────────────────────┤
│  DP1. Learner Ownership          DP2. Scaffold Rather Than Substitute      │
│  DP3. Reflection Before Correction  DP4. Continuous Knowledge Integration  │
└─────────────────────────────────────────────────────────────────────────────┘
                                    ↓
┌─────────────────────────────────────────────────────────────────────────────┐
│                    INTERACTION MECHANISM                                    │
├─────────────────────────────────────────────────────────────────────────────┤
│                                                                             │
│   ┌──────────┐    ┌──────────┐    ┌──────────┐    ┌──────────┐            │
│   │ CONSTRUCT│───→│ REFLECT  │───→│ SCAFFOLD │───→│CONSOLIDATE│───┐       │
│   │  (Learner│    │(Learner +│    │(AI prompts│    │(Learner  │   │       │
│   │  authors)│    │ AI asks) │    │ + hints)  │    │ applies) │   │       │
│   └──────────┘    └──────────┘    └──────────┘    └──────────┘   │       │
│        ↑              ↑              ↑              ↑             │       │
│        │              │              │              │             │       │
│        └──────────────┴──────────────┴──────────────┴─────────────┘       │
│                                   ↓                                        │
│                          ┌──────────────┐                                 │
│                          │   REVISIT    │                                 │
│                          │(AI connects, │                                 │
│                          │ learner      │                                 │
│                          │  integrates) │                                 │
│                          └──────────────┘                                 │
│                                   ↓                                        │
│                        ┌────────────────────┐                             │
│                        │  Personal Wiki     │                             │
│                        │  (Evolving         │                             │
│                        │   Knowledge Base)  │                             │
│                        └────────────────────┘                             │
└─────────────────────────────────────────────────────────────────────────────┘
                                    ↓
┌─────────────────────────────────────────────────────────────────────────────┐
│                    OUTCOMES                                                 │
├─────────────────────────────────────────────────────────────────────────────┤
│  • Epistemic Agency Preserved    • Deep Conceptual Understanding          │
│  • Metacognitive Development     • Cumulative Knowledge Integration       │
│  • Reduced Cognitive Offloading  • Transferable Skills                    │
└─────────────────────────────────────────────────────────────────────────────┘</code></pre>
<p><em>The framework integrates three theoretical traditions (writing-to-learn, metacognition/SRL, and personal knowledge management) through four design principles, operationalised via a five-stage recursive cycle with the Prompt Before Provide mechanism. Learner agency is preserved throughout, with AI serving as scaffolder rather than substitute.</em></p>
<hr>
</section>
</section>
<section id="proposed-ai-wiki-companion" class="level2">
<h2 class="anchored" data-anchor-id="proposed-ai-wiki-companion">3. Proposed AI Wiki Companion</h2>
<section id="design-rationale" class="level3">
<h3 class="anchored" data-anchor-id="design-rationale">3.1 Design Rationale</h3>
<p>The proposed AI Wiki Companion is conceptualised as a personal learning environment rather than as an automated knowledge-production tool. Its design seeks to maintain an intentional asymmetry between learner and AI responsibilities. The learner authors explanations, determines conceptual relationships, evaluates feedback, and decides how knowledge should be revised. The AI Companion provides adaptive prompts intended to expose gaps, elicit explanation, provoke reconsideration, and connect current activity with prior knowledge.</p>
<p><strong>Table 1. Design principles of the AI Wiki Companion</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 11%">
<col style="width: 21%">
<col style="width: 27%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Design Principle</th>
<th>Definition</th>
<th>Pedagogical Rationale</th>
<th>Intended System Implication</th>
<th>Operational Indicator</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>DP1. Learner Ownership</strong></td>
<td>The learner authors and retains control over the primary knowledge artefact.</td>
<td>Preserves epistemic agency and ensures that the personal wiki represents learner-mediated understanding rather than unexamined AI output.</td>
<td>AI-generated suggestions require explicit learner judgement before incorporation; the system does not silently overwrite learner-authored text.</td>
<td>100% of AI suggestions require explicit learner approval; revision history preserves both learner and AI contributions separately.</td>
</tr>
<tr class="even">
<td><strong>DP2. Scaffold Rather Than Substitute</strong></td>
<td>AI supports cognitive activity without automatically performing learning-relevant intellectual work on the learner’s behalf.</td>
<td>Reduces inappropriate cognitive substitution and retains opportunities for explanation, reasoning, synthesis, and retrieval.</td>
<td>When appropriate, AI provides prompts, hints, questions, or partial scaffolds before complete explanations.</td>
<td>Prompt Before Provide mechanism: AI first requests learner explanation before providing direct answers in 80%+ of interactions.</td>
</tr>
<tr class="odd">
<td><strong>DP3. Reflection Before Correction</strong></td>
<td>Learners are encouraged to inspect and reconsider their reasoning before direct correction is supplied.</td>
<td>Supports metacognitive monitoring and SRL by making discrepancies in understanding an object of learner attention.</td>
<td>Potential misconceptions or incomplete explanations initially trigger reflective questions rather than automatic rewriting.</td>
<td>Metacognitive prompts precede corrective feedback; minimum 1 reflection step required before correction suggestions.</td>
</tr>
<tr class="even">
<td><strong>DP4. Continuous Knowledge Integration</strong></td>
<td>New learning is related to previously constructed knowledge and may trigger revision of earlier representations.</td>
<td>Supports cumulative and relational knowledge development rather than isolated task completion.</td>
<td>The system retrieves relevant prior entries and recommends relationships, contradictions, or opportunities for revision.</td>
<td>Cross-entry relationship detection; automatic suggestions for revisiting prior entries when new concepts are added.</td>
</tr>
</tbody>
</table>
<p>These principles are not intended to prohibit direct AI assistance. There are circumstances in which explicit explanation is appropriate and efficient. The design question is instead whether immediate provision of a completed answer would displace cognitive activity that the learning task was intended to elicit. The proposed framework therefore makes the timing and form of AI assistance pedagogically consequential.</p>
<p><strong>Design trade-offs:</strong></p>
<p>The framework acknowledges several inherent tensions that require careful balancing:</p>
<ol type="1">
<li><p><strong>Efficiency vs.&nbsp;Cognitive Effort:</strong> While AI could provide instant, complete answers, doing so may remove productive struggle. The framework prioritises learning-relevant effort over task completion speed, but allows learners to request direct assistance when appropriate.</p></li>
<li><p><strong>Guidance vs.&nbsp;Autonomy:</strong> Too much scaffolding can become intrusive; too little can leave learners unsupported. The framework uses adaptive defaults (Prompt Before Provide) while maintaining learner control to override or skip scaffolding steps.</p></li>
<li><p><strong>Automation vs.&nbsp;Learner Control:</strong> Full automation would maximise efficiency but undermine epistemic agency. The framework deliberately maintains learner control over all knowledge artefact modifications, even at the cost of reduced convenience.</p></li>
<li><p><strong>Structure vs.&nbsp;Flexibility:</strong> The 5-stage cycle provides structure, but learning is not always linear. The framework supports recursive progression (returning to earlier stages) while maintaining clear stage boundaries for reflection.</p></li>
</ol>
<p>These trade-offs are not resolved definitively but are instead made explicit and manageable through the design principles and interaction mechanisms described below.</p>
</section>
<section id="ai-supported-knowledge-construction-cycle" class="level3">
<h3 class="anchored" data-anchor-id="ai-supported-knowledge-construction-cycle">3.2 AI-Supported Knowledge Construction Cycle</h3>
<p>The four design principles are operationalised through the five-stage <strong>Construct → Reflect → Scaffold → Consolidate &amp; Apply → Revisit &amp; Extend</strong> cycle. The cycle is recursive rather than strictly linear. A learner may return to an earlier stage when reflection reveals insufficient understanding, when application exposes a misconception, or when new material requires an existing wiki entry to be reconsidered.</p>
<p><strong>Table 2. Five-stage AI-supported knowledge construction cycle</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 25%">
<col style="width: 19%">
<col style="width: 26%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Stage</th>
<th>Primary Learner Activity</th>
<th>AI Companion Role</th>
<th>Intended Learning Process</th>
<th>Example Interaction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Construct</strong></td>
<td>Develops an initial explanation, example, representation, or conceptual relationship in the personal wiki.</td>
<td>Maintains limited intervention and may provide task framing without constructing the artefact.</td>
<td>Externalisation, generative processing, activation of prior knowledge.</td>
<td>Learner writes: “Overfitting happens when the model memorises the training data.” AI does not auto-correct.</td>
</tr>
<tr class="even">
<td><strong>Reflect</strong></td>
<td>Examines confidence, completeness, assumptions, and explanatory adequacy.</td>
<td>Generates metacognitive and Socratic prompts grounded in the learner’s artefact.</td>
<td>Metacognitive monitoring and self-evaluation.</td>
<td>AI asks: “Your explanation mentions memorisation. How does this relate to generalisation performance on unseen data?”</td>
</tr>
<tr class="odd">
<td><strong>Scaffold</strong></td>
<td>Responds to identified gaps, challenges, or possible misconceptions.</td>
<td>Provides targeted questions, hints, connection suggestions, and evidence prompts.</td>
<td>Elaborative processing, conceptual restructuring, guided reasoning.</td>
<td>Learner revises: “Oh right—overfitting means good training accuracy but poor test accuracy.” AI confirms and adds connection to regularisation.</td>
</tr>
<tr class="even">
<td><strong>Consolidate &amp; Apply</strong></td>
<td>Retrieves, explains, compares, predicts, solves, or transfers knowledge to a new context.</td>
<td>Generates retrieval and application tasks and provides subsequent formative feedback.</td>
<td>Retrieval practice, consolidation, transfer, evaluative judgement.</td>
<td>AI suggests: “How would this concept apply to a neural network with many layers vs.&nbsp;a simple linear regression?”</td>
</tr>
<tr class="odd">
<td><strong>Revisit &amp; Extend</strong></td>
<td>Integrates new concepts with previously constructed knowledge and revises earlier entries where appropriate.</td>
<td>Identifies potentially relevant prior knowledge and prompts comparison, integration, or revision.</td>
<td>Longitudinal integration and cumulative knowledge construction.</td>
<td>Two weeks later: AI flags that the overfitting entry could be improved with the learner’s new understanding of dropout.</td>
</tr>
</tbody>
</table>
<p><strong>Figure 2. The Five-Stage Knowledge Construction Cycle</strong></p>
<pre><code>                              ┌─────────────────────────────────────────┐
                              │                                         │
                              ▼                                         │
    ┌─────────────┐      ┌──────────┐      ┌──────────┐                │
    │  CONSTRUCT  │─────▶│ REFLECT  │─────▶│ SCAFFOLD │                │
    │             │      │          │      │          │                │
    │ • Write     │      │ • Answer │      │ • AI     │                │
    │   initial   │      │   meta-  │      │   detects│                │
    │   explan-   │      │   cogni- │      │   gaps   │                │
    │   ation     │      │   tive   │      │ • AI     │                │
    │ • Activate  │      │   ques-  │      │   sug-   │                │
    │   prior     │      │   tions  │      │   gests  │                │
    │   knowledge │      │ • Self-  │      │   con-   │                │
    │ • External- │      │   assess │      │   nec-   │                │
    │   ise under-│      │   under- │      │   tions  │                │
    │   standing  │      │   stand- │      │ • Pro-   │                │
    │             │      │   ing    │      │   vide   │                │
    └─────────────┘      └──────────┘      │   hints  │                │
          ▲                                 └──────────┘                │
          │                                       │                     │
          │                                       ▼                     │
          │                                 ┌─────────────┐             │
          │                                 │ CONSOLIDATE │             │
          │                                 │             │             │
          │                                 │ • Apply to  │             │
          │                                 │   new prob- │             │
          │                                 │   lem       │             │
          │                                 │ • Compare   │             │
          │                                 │   concepts  │             │
          │                                 │ • Test      │             │
          │                                 │   under-    │             │
          │                                 │   standing  │             │
          │                                 └─────────────┘             │
          │                                       │                     │
          │                                       ▼                     │
          │                                 ┌─────────────┐             │
          │                                 │   REVISIT   │             │
          │                                 │             │             │
          │                                 │ • Connect   │             │
          │                                 │   to prior  │             │
          │                                 │   knowledge │             │
          │                                 │ • Update    │             │
          │                                 │   existing  │             │
          │                                 │   entries   │             │
          │                                 │ • Build     │             │
          │                                 │   concept   │             │
          │                                 │   network   │             │
          │                                 └─────────────┘             │
          │                                       │                     │
          └───────────────────────────────────────┘                     │
                    (Recursive iteration)                                │</code></pre>
<p><em>The learning cycle is recursive, not linear. Learners may return to earlier stages when they discover gaps (e.g., during Scaffold or Consolidate), when reflection reveals incomplete understanding, or when new knowledge requires revising prior entries. This recursive nature supports iterative refinement and deep conceptual integration over time.</em></p>
<p><strong>Operational mechanism: Prompt Before Provide</strong></p>
<p>The core interaction mechanism across all stages is the <strong>Prompt Before Provide</strong> principle. When a learner’s input suggests a potential gap or misconception, the AI Companion follows a hierarchical response strategy:</p>
<ol type="1">
<li><strong>Stage 1: Metacognitive Prompt</strong> (first response)
<ul>
<li>“What part of this explanation are you least confident about?”</li>
<li>“Does this account for [relevant factor]?”</li>
<li>“How would you test whether this claim is correct?”</li>
</ul></li>
<li><strong>Stage 2: Socratic Questioning</strong> (if learner indicates uncertainty)
<ul>
<li>“You mentioned X. How does that connect to Y?”</li>
<li>“If your explanation were true, what would we expect to observe in [scenario]?”</li>
<li>“What evidence would contradict your claim?”</li>
</ul></li>
<li><strong>Stage 3: Guided Hint</strong> (if learner still struggles)
<ul>
<li>“Consider the relationship between [concept A] and [concept B]”</li>
<li>“Think about [specific aspect] you haven’t mentioned yet”</li>
<li>“What if we approached this from [alternative perspective]?”</li>
</ul></li>
<li><strong>Stage 4: Partial Scaffold</strong> (if learner requests help)
<ul>
<li>Provide a partial explanation with gaps for learner to fill</li>
<li>Offer a worked example with key steps missing</li>
<li>Suggest a relevant resource without summarising it</li>
</ul></li>
<li><strong>Stage 5: Direct Answer</strong> (only if explicitly requested or after learner attempts)
<ul>
<li>Provide complete explanation</li>
<li>Always follow with reflective question: “Does this clarify your original question?”</li>
</ul></li>
</ol>
<p>This hierarchical approach ensures that AI assistance is proportionate to learner need and that cognitive effort is retained at each stage. The learner can skip stages by explicitly requesting direct assistance, but the default path prioritises productive struggle.</p>
<p><strong>Recursive cycle dynamics:</strong></p>
<p>The 5-stage cycle is not a rigid workflow but a flexible pattern. Typical learner trajectories include:</p>
<ul>
<li><strong>Linear progression:</strong> Construct → Reflect → Scaffold → Consolidate → (complete)</li>
<li><strong>Reflective iteration:</strong> Construct → Reflect → (realise gap) → Construct (revise) → Reflect → Scaffold</li>
<li><strong>Deep exploration:</strong> Construct → Reflect → Scaffold → (new question) → Construct (new entry) → …</li>
<li><strong>Longitudinal revisiting:</strong> Construct → … → (weeks later) → Revisit &amp; Extend → Construct (revision)</li>
</ul>
<p>The system tracks these trajectories to adapt scaffolding intensity. For example, if a learner frequently skips reflection, the system may increase the prominence of reflective prompts. If a learner consistently requests direct answers, the system may offer a brief explanation of why productive struggle matters for that particular concept.</p>
<section id="construct" class="level4">
<h4 class="anchored" data-anchor-id="construct">3.2.1 Construct</h4>
<p>The Construct stage establishes learner authorship as the starting condition of the interaction. Rather than asking AI to generate a complete knowledge entry, the learner first articulates a concept using existing knowledge and available learning resources. This may involve writing an explanation, providing an example, identifying relevant evidence, or linking the concept to an existing wiki page.</p>
<p>For example, a learner encountering overfitting may initially write that a model overfits when it learns the training data too closely. Although incomplete, this representation provides evidence of the learner’s present understanding. Premature AI rewriting would remove the opportunity to examine that representation. AI involvement is consequently restricted during initial construction unless assistance is required to overcome a barrier that would otherwise prevent meaningful participation.</p>
</section>
<section id="reflect" class="level4">
<h4 class="anchored" data-anchor-id="reflect">3.2.2 Reflect</h4>
<p>During Reflect, the learner is encouraged to inspect the adequacy of the constructed artefact before receiving substantive correction. Contextual prompts may ask which part of an explanation is least certain, whether the learner can restate the concept without consulting the wiki, what assumptions underpin the explanation, or whether a counterexample can be generated.</p>
<p>The purpose is to encourage metacognitive monitoring and to establish a discrepancy, where appropriate, between what the learner currently believes and what additional understanding may be required. This stage gives operational form to <strong>DP3, Reflection Before Correction</strong>, and is intended to reduce the tendency for AI feedback to become passively consumed evaluative information.</p>
</section>
<section id="scaffold" class="level4">
<h4 class="anchored" data-anchor-id="scaffold">3.2.3 Scaffold</h4>
<p>The Scaffold stage introduces more explicit AI support after the learner’s current representation and reflection are available. The AI Companion may identify an omitted concept, challenge a weak relationship, highlight a potentially questionable assumption, ask for evidence, or suggest that another wiki entry is conceptually relevant.</p>
<p>If the learner explains overfitting without referring to generalisation, for instance, the system may ask how the two concepts are related. If regularisation has been linked to overfitting, the AI may request an explanation of why the relationship exists rather than treating the hyperlink itself as evidence of understanding. When a possible misconception is detected, the system frames it as an epistemic problem to be investigated.</p>
<p>This mode of interaction conceptualises AI feedback as a trigger for further cognition rather than as a replacement artefact.</p>
</section>
<section id="consolidate-apply" class="level4">
<h4 class="anchored" data-anchor-id="consolidate-apply">3.2.4 Consolidate &amp; Apply</h4>
<p>The Consolidate &amp; Apply stage recognises that possession of an accurate written note does not necessarily demonstrate retrievable or transferable understanding. Learners are therefore required to use knowledge independently of the stored artefact. Tasks may involve free recall, explanation, comparison, prediction, problem solving, or application to a novel situation.</p>
<p>For example, after developing an entry on overfitting, a learner might first be asked to explain the concept without consulting the wiki. The system could subsequently present a scenario in which training accuracy is substantially higher than test accuracy and ask the learner to diagnose the problem and compare possible interventions. Such progression creates a distinction between the quality of the external artefact and the learner’s capacity to use the represented knowledge.</p>
</section>
<section id="revisit-extend" class="level4">
<h4 class="anchored" data-anchor-id="revisit-extend">3.2.5 Revisit &amp; Extend</h4>
<p>The Revisit &amp; Extend stage differentiates the proposed model from one-off AI-assisted writing. The personal knowledge base persists across learning episodes. When a learner later adds cross-validation, for example, the AI Companion may retrieve earlier entries on overfitting, generalisation, train-test split, and model evaluation. Rather than automatically creating new links, it can ask whether and how the new concept modifies the learner’s earlier understanding.</p>
<p>Knowledge construction is therefore treated as cumulative and revisable. Earlier explanations are not regarded as completed products but as representations that may require refinement when the learner encounters new evidence, theoretical perspectives, or applications.</p>
</section>
</section>
<section id="prompt-before-provide" class="level3">
<h3 class="anchored" data-anchor-id="prompt-before-provide">3.3 Prompt Before Provide</h3>
<p>The <strong>Prompt Before Provide</strong> interaction model provides a concrete HCI mechanism for implementing the broader scaffold-rather-than-substitute principle. The mechanism applies particularly when the learner requests information about a concept that is itself an appropriate object of retrieval or explanation.</p>
<p>For example, when a learner asks, <em>“What is polymorphism?”</em>, a conventional conversational assistant may immediately provide a definition. Under Prompt Before Provide, the AI Companion may first ask the learner to describe their present understanding in two or three sentences. The subsequent system response can then be calibrated to the learner-generated representation.</p>
<p>Prompt Before Provide is not intended as an absolute prohibition against direct instruction. Requiring prior production in every interaction could increase unnecessary cognitive load, frustrate learners, or become pedagogically inappropriate when prerequisite knowledge is absent. Instead, the mechanism represents an adaptive default when learner retrieval, explanation, or self-assessment is itself educationally valuable.</p>
<p>The approach therefore seeks to balance two forms of support: <strong>productive effort</strong>, in which learners are given sufficient opportunity to reason, retrieve, and construct; and <strong>instructional assistance</strong>, in which AI supplies information when additional learner effort is unlikely to be educationally productive.</p>
<p><strong>Algorithmic implementation:</strong></p>
<p>The Prompt Before Provide mechanism follows a decision tree that determines whether to request learner production or provide direct assistance:</p>
<pre><code>function getAIResponse(learnerQuery, learnerContext):
    if learnerQuery.isDirectRequestForAnswer():
        if learnerHasPrerequisiteKnowledge(learnerContext):
            return metacognitivePrompt(learnerQuery)
        else:
            return briefExplanation(learnerQuery) + reflectiveQuestion()
    
    if learnerQuery.containsPotentialMisconception():
        return socraticQuestion(learnerQuery.misconception)
    
    if learnerQuery.isIncompleteExplanation():
        return gapIdentification(learnerQuery) + connectionSuggestion()
    
    if learnerQuery.requestsDirectHelp():
        if learnerHasAttemptedExplanation():
            return partialScaffold(learnerQuery)
        else:
            return encourageFirstAttempt(learnerQuery)
    
    return defaultScaffolding(learnerQuery, learnerContext)</code></pre>
<p><strong>Calibration to learner expertise:</strong></p>
<p>The mechanism adapts to learner expertise through three modes:</p>
<ol type="1">
<li><strong>Novice mode:</strong> Higher threshold for direct assistance; more scaffolding prompts; emphasis on building foundational understanding</li>
<li><strong>Intermediate mode:</strong> Standard Prompt Before Provide; balanced scaffolding and direct instruction</li>
<li><strong>Advanced mode:</strong> Lower threshold for productive struggle; more open-ended questions; learner can request direct answers more frequently</li>
</ol>
<p>Mode selection is based on: - Prior interaction history (completion rates, scaffolding acceptance) - Self-reported confidence - Performance on application tasks - Explicit learner preference</p>
<p><strong>Pedagogical rationale:</strong></p>
<p>The Prompt Before Provide mechanism is grounded in three theoretical considerations:</p>
<ol type="1">
<li><p><strong>Generation effect:</strong> Learner-generated explanations are better remembered than passively consumed information (Fiorella and Mayer, 2015)</p></li>
<li><p><strong>Metacognitive calibration:</strong> Self-assessment before feedback improves accuracy of metacognitive monitoring (Dunlosky and Metcalfe, 2009)</p></li>
<li><p><strong>Cognitive agency preservation:</strong> Maintaining learner control over knowledge construction reduces risks of cognitive offloading (Kim and Lee, 2026)</p></li>
</ol>
</section>
<section id="core-ai-companion-functions" class="level3">
<h3 class="anchored" data-anchor-id="core-ai-companion-functions">3.4 Core AI Companion Functions</h3>
<p>The pedagogical framework is translated into a set of AI functions detailed in Table 3. These functions are organised according to the cognitive or metacognitive activity they are intended to stimulate rather than according to the generative capability of the underlying model.</p>
<p><strong>Table 3. AI Wiki Companion functions and intended learning roles</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 33%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th>AI Wiki Function</th>
<th>Intended Learning Role</th>
<th>Illustrative Intervention</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Socratic Questioning</strong></td>
<td>Elicit explanation, justification, comparison, and reasoning.</td>
<td>“Why does this relationship hold?”</td>
</tr>
<tr class="even">
<td><strong>Knowledge Gap Detection</strong></td>
<td>Draw attention to concepts or relationships that may be incomplete.</td>
<td>“Your explanation discusses training performance but not generalisation. Is anything missing?”</td>
</tr>
<tr class="odd">
<td><strong>Connection Recommendation</strong></td>
<td>Encourage integration of new and existing knowledge.</td>
<td>“Could this concept be related to your earlier entry on the bias–variance trade-off?”</td>
</tr>
<tr class="even">
<td><strong>Misconception Challenge</strong></td>
<td>Prompt reconsideration of potentially inaccurate reasoning.</td>
<td>“Would this claim remain true for unseen data?”</td>
</tr>
<tr class="odd">
<td><strong>Evidence Prompting</strong></td>
<td>Encourage verification and justification of knowledge claims.</td>
<td>“What source or evidence supports this statement?”</td>
</tr>
<tr class="even">
<td><strong>Retrieval &amp; Application Questions</strong></td>
<td>Promote recall, consolidation, and transfer.</td>
<td>“Explain the concept without consulting the wiki, then apply it to this scenario.”</td>
</tr>
<tr class="odd">
<td><strong>Review/Revisit Recommendation</strong></td>
<td>Encourage longitudinal refinement of earlier knowledge.</td>
<td>“Does what you have just learned require your earlier model-evaluation entry to be revised?”</td>
</tr>
<tr class="even">
<td><strong>Source Recommendation</strong></td>
<td>Direct the learner towards potentially relevant evidence while preserving verification responsibility.</td>
<td>“This source may be relevant. Verify its claims before integrating it into your wiki.”</td>
</tr>
</tbody>
</table>
<p>Source recommendation warrants particular caution because LLM-generated citations and resource descriptions may be inaccurate. The learner must therefore verify recommended material before incorporating it into the personal knowledge base. Where technically feasible, retrieval should be grounded in verified scholarly databases or instructor-approved corpora rather than unconstrained model generation.</p>
</section>
<section id="conceptual-system-architecture" class="level3">
<h3 class="anchored" data-anchor-id="conceptual-system-architecture">3.5 Conceptual System Architecture</h3>
<p>The proposed architecture consists of the <strong>Wiki Editor</strong>, <strong>Personal Knowledge Base</strong>, <strong>Concept Graph</strong>, <strong>Knowledge Context</strong>, and <strong>AI Companion</strong>.</p>
<p>The <strong>Wiki Editor</strong> constitutes the primary learner-facing authoring environment. It supports the creation and revision of knowledge entries while making AI-generated interventions distinguishable from learner-authored text. Revision histories should preserve changes over time, enabling both learner reflection and research analysis.</p>
<p>The <strong>Personal Knowledge Base</strong> stores learner-generated explanations, examples, tags, evidence, links, and previous revisions. It functions as the persistent substrate through which the system supports longitudinal knowledge development.</p>
<p>The <strong>Concept Graph</strong> represents explicit relationships among wiki entries. These relationships may arise from learner-created links or system-detected candidate associations. Importantly, automatically detected associations remain recommendations until learners determine whether they constitute meaningful conceptual relationships.</p>
<p>The <strong>Knowledge Context</strong> component selects relevant information from the Personal Knowledge Base and Concept Graph for a particular AI interaction. Context selection is necessary because an unconstrained personal knowledge base may exceed model context limits and may contain material irrelevant to the immediate learning task. Retrieval should therefore prioritise conceptually related entries, recent revisions, prerequisite concepts, and previously identified misconceptions.</p>
<p>Finally, the <strong>AI Companion</strong> uses the selected Knowledge Context together with the learner’s current artefact and interaction history to determine an appropriate scaffolding response. Depending on the stage of the knowledge-construction cycle, this response may take the form of a reflective prompt, Socratic question, misconception challenge, connection recommendation, retrieval task, or application problem.</p>
<p>The architecture can be represented conceptually as:</p>
<pre><code>Learner → Wiki Editor → Personal Knowledge Base → Concept Graph → Knowledge Context → AI Companion → Scaffold → Learner Evaluation → Wiki Revision</code></pre>
<p>Crucially, the final transition returns to the learner rather than directly to the Personal Knowledge Base. This design choice operationalises learner-in-the-loop control: AI recommendations must be interpreted and acted upon by the learner before they become part of the persistent knowledge artefact.</p>
</section>
<section id="prototype-implementation" class="level3">
<h3 class="anchored" data-anchor-id="prototype-implementation">3.6 Prototype Implementation</h3>
<p>To evaluate the feasibility of the proposed framework, a functional prototype was developed implementing the five-stage knowledge construction cycle. This section describes the technical architecture, implementation decisions, and current capabilities of the prototype.</p>
<section id="system-architecture" class="level4">
<h4 class="anchored" data-anchor-id="system-architecture">3.6.1 System Architecture</h4>
<p>The prototype follows a client-server architecture with three main components:</p>
<p><strong>Frontend (Client-Side):</strong> - <strong>Technology:</strong> HTML5, CSS3, JavaScript (ES6+) - <strong>Framework:</strong> Vanilla JavaScript with modular class-based design - <strong>UI Components:</strong> AI Companion sidebar (718 lines), responsive layout, modal dialogs - <strong>Key Features:</strong> - Five-stage cycle interface (Construct, Reflect, Scaffold, Consolidate, Revisit) - Real-time API communication with error handling - Local state management for concept selection and user input - Visual feedback for API responses (success/error messages)</p>
<p><strong>Backend (Server-Side):</strong> - <strong>Technology:</strong> Python 3.10+, Flask web framework - <strong>Database:</strong> JSON-based file storage (user-specific wiki data) - <strong>API Endpoints:</strong> Five RESTful endpoints corresponding to the five stages - <strong>Key Features:</strong> - User authentication and data isolation - Revision history tracking - Mock scaffolding templates (no real LLM in current version) - CORS-enabled for cross-origin frontend access</p>
<p><strong>Data Persistence:</strong> - <strong>Storage Format:</strong> JSON files per user (<code>_data/users/{username}/wiki_data.json</code>) - <strong>Schema:</strong> Concept-keyed dictionary with entries containing explanation, revision history, timestamps - <strong>Backup:</strong> Automatic versioning with timestamp-based revision IDs</p>
</section>
<section id="api-design" class="level4">
<h4 class="anchored" data-anchor-id="api-design">3.6.2 API Design</h4>
<p>The backend exposes five endpoints, each corresponding to a stage in the knowledge construction cycle:</p>
<p><strong>Table 4. API Endpoints and Functions</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 16%">
<col style="width: 25%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Endpoint</th>
<th>HTTP Method</th>
<th>Purpose</th>
<th>Request Body</th>
<th>Response</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>/api/wiki/construct</code></td>
<td>POST</td>
<td>Save learner explanation</td>
<td><code>{concept, explanation}</code></td>
<td><code>{success, entry_id, message}</code></td>
</tr>
<tr class="even">
<td><code>/api/wiki/reflect</code></td>
<td>POST</td>
<td>Generate metacognitive prompts</td>
<td><code>{concept, explanation, use_llm}</code></td>
<td><code>{success, prompt, mode}</code></td>
</tr>
<tr class="odd">
<td><code>/api/wiki/scaffold</code></td>
<td>POST</td>
<td>Detect gaps and suggest connections</td>
<td><code>{concept, explanation, action, use_llm}</code></td>
<td><code>{success, missing_concepts, suggestions, mode}</code></td>
</tr>
<tr class="even">
<td><code>/api/wiki/consolidate</code></td>
<td>POST</td>
<td>Generate application tasks</td>
<td><code>{concept, original, retrieval_attempt, use_llm}</code></td>
<td><code>{success, task, mode}</code></td>
</tr>
<tr class="odd">
<td><code>/api/wiki/revisit</code></td>
<td>POST</td>
<td>Retrieve related concepts</td>
<td><code>{concept}</code></td>
<td><code>{success, related_entries, prompts, mode}</code></td>
</tr>
</tbody>
</table>
<p>Each endpoint accepts a <code>use_llm</code> flag (currently set to <code>false</code>) to toggle between mock template responses and real LLM-generated scaffolding. This design allows future integration of large language models without modifying the frontend.</p>
</section>
<section id="mock-scaffolding-implementation" class="level4">
<h4 class="anchored" data-anchor-id="mock-scaffolding-implementation">3.6.3 Mock Scaffolding Implementation</h4>
<p>The current prototype uses template-based scaffolding rather than real LLM responses. This design decision was motivated by three considerations:</p>
<ol type="1">
<li><strong>Cost efficiency:</strong> Avoids API costs during pilot testing</li>
<li><strong>Predictability:</strong> Ensures consistent scaffolding quality across participants</li>
<li><strong>Debugging:</strong> Simplifies troubleshooting during development</li>
</ol>
<p>The mock knowledge base contains pre-defined scaffolding for three machine learning concepts:</p>
<p><strong>Example: Overfitting scaffolding</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"overfitting"</span>: {</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">"reflection_prompts"</span>: [</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>            <span class="st">"What part of your explanation are you most confident about?"</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>            <span class="st">"What part are you least confident about?"</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">"What questions remain unanswered?"</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">"missing_concepts"</span>: [<span class="st">"regularisation"</span>, <span class="st">"cross-validation"</span>, <span class="st">"bias-variance tradeoff"</span>],</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"suggestions"</span>: [</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Consider how regularisation helps prevent overfitting"</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Think about how cross-validation detects overfitting"</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">"consolidation_task"</span>: <span class="st">"You're training a model and notice high training accuracy but low validation accuracy. What's happening and what would you do?"</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>When a learner requests scaffolding for a concept not in the mock knowledge base, the system returns generic prompts: - Reflection: “What part of your explanation are you most confident about?” - Scaffold: “Consider exploring related concepts and their relationships” - Consolidate: “Try applying this concept to a real-world scenario”</p>
</section>
<section id="frontend-backend-integration" class="level4">
<h4 class="anchored" data-anchor-id="frontend-backend-integration">3.6.4 Frontend-Backend Integration</h4>
<p>The frontend <code>AICompanion</code> class (718 lines) manages the five-stage cycle through a state machine pattern:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode javascript code-with-copy"><code class="sourceCode javascript"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> AICompanion {</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">constructor</span>(config) {</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">this</span><span class="op">.</span><span class="at">apiBase</span> <span class="op">=</span> config<span class="op">.</span><span class="at">apiBase</span> <span class="op">||</span> <span class="st">'http://localhost:5001/api/wiki'</span><span class="op">;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="kw">this</span><span class="op">.</span><span class="at">currentConcept</span> <span class="op">=</span> <span class="kw">null</span><span class="op">;</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="kw">this</span><span class="op">.</span><span class="at">currentMode</span> <span class="op">=</span> <span class="kw">null</span><span class="op">;</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">this</span><span class="op">.</span><span class="at">userExplanation</span> <span class="op">=</span> <span class="kw">null</span><span class="op">;</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="kw">async</span> <span class="fu">_callAPI</span>(mode<span class="op">,</span> payload<span class="op">,</span> callback) {</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="co">// Map mode to endpoint</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="kw">const</span> endpointMap <span class="op">=</span> {</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>      <span class="st">'construct'</span><span class="op">:</span> <span class="st">'/construct'</span><span class="op">,</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>      <span class="st">'reflect'</span><span class="op">:</span> <span class="st">'/reflect'</span><span class="op">,</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>      <span class="st">'scaffold'</span><span class="op">:</span> <span class="st">'/scaffold'</span><span class="op">,</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>      <span class="st">'consolidate'</span><span class="op">:</span> <span class="st">'/consolidate'</span><span class="op">,</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>      <span class="st">'revisit'</span><span class="op">:</span> <span class="st">'/revisit'</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    }<span class="op">;</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    <span class="kw">const</span> response <span class="op">=</span> <span class="cf">await</span> <span class="fu">fetch</span>(<span class="vs">`</span><span class="sc">${</span><span class="kw">this</span><span class="op">.</span><span class="at">apiBase</span><span class="sc">}${</span>endpointMap[mode]<span class="sc">}</span><span class="vs">`</span><span class="op">,</span> {</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>      <span class="dt">method</span><span class="op">:</span> <span class="st">'POST'</span><span class="op">,</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>      <span class="dt">headers</span><span class="op">:</span> { <span class="st">'Content-Type'</span><span class="op">:</span> <span class="st">'application/json'</span> }<span class="op">,</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>      <span class="dt">body</span><span class="op">:</span> <span class="bu">JSON</span><span class="op">.</span><span class="fu">stringify</span>(payload)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    })<span class="op">;</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    <span class="kw">const</span> data <span class="op">=</span> <span class="cf">await</span> response<span class="op">.</span><span class="fu">json</span>()<span class="op">;</span></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">callback</span>(data)<span class="op">;</span></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The integration implements the <strong>Prompt Before Provide</strong> principle by: 1. Requiring learner input before generating scaffolding 2. Displaying reflection prompts before showing gap detection 3. Asking learners to attempt consolidation before receiving feedback</p>
</section>
<section id="current-capabilities-and-limitations" class="level4">
<h4 class="anchored" data-anchor-id="current-capabilities-and-limitations">3.6.5 Current Capabilities and Limitations</h4>
<p><strong>Implemented Features:</strong> - ✅ Five-stage knowledge construction cycle - ✅ Real-time API communication - ✅ Data persistence with revision history - ✅ Error handling and user feedback - ✅ Mock scaffolding for 3 ML concepts - ✅ Responsive UI design - ✅ CORS-enabled cross-origin access</p>
<p><strong>Known Limitations:</strong> - ⚠️ No real LLM integration (mock responses only) - ⚠️ Limited concept coverage (3 ML concepts) - ⚠️ No concept navigation between pages - ⚠️ No offline mode - ⚠️ No mobile optimization testing</p>
<p><strong>Future Enhancements:</strong> 1. <strong>LLM Integration:</strong> Replace mock responses with real LLM-generated scaffolding 2. <strong>Expanded Knowledge Base:</strong> Add scaffolding for additional concepts 3. <strong>Concept Graph:</strong> Implement automatic relationship detection 4. <strong>Analytics Dashboard:</strong> Visualize learner progress and interaction patterns 5. <strong>Multi-User Support:</strong> Enable collaborative knowledge construction</p>
</section>
<section id="deployment-and-access" class="level4">
<h4 class="anchored" data-anchor-id="deployment-and-access">3.6.6 Deployment and Access</h4>
<p>The prototype is deployed as a local web application: - <strong>Frontend:</strong> Served via Python HTTP server on port 8000 - <strong>Backend:</strong> Flask API server on port 5001 - <strong>Access URL:</strong> <code>http://localhost:8000/ai-wiki.html</code> - <strong>Browser Support:</strong> Chrome, Firefox, Safari (tested)</p>
<p>The system is designed for easy deployment on institutional servers or cloud platforms. All dependencies are specified in <code>requirements.txt</code> (Python) and can be installed via <code>pip install -r requirements.txt</code>.</p>
<hr>
</section>
</section>
</section>
<section id="formative-evaluation" class="level2">
<h2 class="anchored" data-anchor-id="formative-evaluation">4. Formative Evaluation</h2>
<section id="evaluation-purpose" class="level3">
<h3 class="anchored" data-anchor-id="evaluation-purpose">4.1 Evaluation Purpose</h3>
<p>The initial evaluation was framed as a formative investigation of the framework and prototype rather than as definitive evidence of long-term learning effectiveness. Its purpose was to examine whether the proposed interaction mechanisms were usable, whether learners engaged with AI scaffolding as intended, and whether preliminary changes could be observed in conceptual understanding and learner-generated knowledge artefacts.</p>
<p>A mixed-method design was appropriate because the research concerned both outcomes and processes. Quantitative measures captured changes in conceptual performance and artefact characteristics, while interaction logs and qualitative accounts clarified how learners interpreted and responded to AI intervention.</p>
</section>
<section id="participants-and-learning-context" class="level3">
<h3 class="anchored" data-anchor-id="participants-and-learning-context">4.2 Participants and Learning Context</h3>
<p>The prototype was evaluated with graduate learners studying machine learning. A technically defined topic was advantageous because conceptual accuracy, relationships, and application could be assessed against relatively clear disciplinary expectations.</p>
<p>For this formative study, the participant sample was reported as a pragmatic exploratory cohort rather than presented as sufficient for population-level causal claims. A subsequent confirmatory study should determine sample size through a priori power analysis based on the intended statistical comparisons and anticipated effect size.</p>
</section>
<section id="procedure" class="level3">
<h3 class="anchored" data-anchor-id="procedure">4.3 Procedure</h3>
<p>The evaluation exposed learners to multiple iterations of the knowledge-construction cycle rather than a single AI interaction. Participants first completed a baseline assessment of conceptual understanding. They then constructed initial personal wiki entries for selected learning concepts. Once an initial representation existed, the AI Companion introduced reflective prompts and targeted scaffolding. Learners decided whether and how to revise their knowledge artefacts before completing retrieval and application tasks. The process was repeated across multiple concepts so that the Revisit &amp; Extend mechanism could be meaningfully observed when later learning related to earlier entries.</p>
<p>A post-intervention assessment examined conceptual understanding and application. Learner perceptions were collected using a transparently developed questionnaire, supplemented by open-ended responses. System logs and wiki revision histories provided additional process data.</p>
</section>
<section id="evaluation-constructs-and-measures" class="level3">
<h3 class="anchored" data-anchor-id="evaluation-constructs-and-measures">4.4 Evaluation Constructs and Measures</h3>
<p>Because the framework distinguished between the external knowledge artefact and internal conceptual understanding, evaluation did not reduce learning to a single outcome measure.</p>
<p><strong>Table 5. Evaluation dimensions and data sources</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 31%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Evaluation Dimension</th>
<th>Indicative Construct</th>
<th>Possible Evidence Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Conceptual Understanding</strong></td>
<td>Accuracy and completeness of disciplinary understanding</td>
<td>Pre-/post-assessment</td>
</tr>
<tr class="even">
<td><strong>Explanation Quality</strong></td>
<td>Depth, coherence, and justification</td>
<td>Wiki artefact rubric</td>
</tr>
<tr class="odd">
<td><strong>Knowledge Integration</strong></td>
<td>Meaningful connections among concepts</td>
<td>Wiki links, Concept Graph, artefact analysis</td>
</tr>
<tr class="even">
<td><strong>Application and Transfer</strong></td>
<td>Ability to use knowledge in unfamiliar situations</td>
<td>Scenario-based or problem-solving tasks</td>
</tr>
<tr class="odd">
<td><strong>Revision Quality</strong></td>
<td>Substantive improvement following reflection or scaffolding</td>
<td>Version history</td>
</tr>
<tr class="even">
<td><strong>Learner Response to AI</strong></td>
<td>Acceptance, rejection, modification, or independent resolution of AI prompts</td>
<td>Interaction logs and revision traces</td>
</tr>
<tr class="odd">
<td><strong>Metacognitive Engagement</strong></td>
<td>Monitoring, confidence judgements, reflection, and explanation of revision decisions</td>
<td>Reflection prompts, questionnaire, interviews</td>
</tr>
<tr class="even">
<td><strong>Perceived Usefulness and Agency</strong></td>
<td>Learner experience of AI feedback, control, and learning support</td>
<td>Questionnaire and qualitative feedback</td>
</tr>
</tbody>
</table>
<p>Artefact quality was examined through dimensions already implied by the framework: conceptual accuracy, explanation depth, meaningful knowledge connections, example quality, appropriate use of evidence, and substantive revision. Such dimensions were operationally defined through a coding rubric and evaluated by multiple raters where feasible. Inter-rater reliability was reported for qualitative or rubric-based coding.</p>
</section>
<section id="human-ai-interaction-analysis" class="level3">
<h3 class="anchored" data-anchor-id="human-ai-interaction-analysis">4.5 Human-AI Interaction Analysis</h3>
<p>A particularly important analytical opportunity concerned what learners actually did with AI-generated scaffolding. Many educational AI evaluations relied primarily on achievement scores or self-reported usefulness. While informative, these measures revealed comparatively little about the mechanism through which AI intervention influenced learning activity.</p>
<p>The proposed system enabled process analysis of the sequence:</p>
<pre><code>AI Feedback → Learner Evaluation → Accept / Reject / Modify → Knowledge Revision</code></pre>
<p>Interaction logs could therefore identify the type of scaffolding delivered, whether the learner engaged with it, whether a corresponding revision occurred, and whether the learner adopted, rejected, or substantially transformed the AI suggestion. Such traces helped distinguish uncritical AI acceptance from active epistemic judgement.</p>
<p>The analysis avoided assuming that acceptance was inherently positive or rejection inherently negative. Rejecting an incorrect, irrelevant, or unnecessary AI suggestion could provide stronger evidence of learner judgement than accepting a valid suggestion. Consequently, the quality of the learner’s reasoning and resulting artefact was more important than maximising AI recommendation acceptance.</p>
</section>
<section id="pilot-study-results" class="level3">
<h3 class="anchored" data-anchor-id="pilot-study-results">4.6 Pilot Study Results</h3>
<p>To evaluate the feasibility and preliminary effectiveness of the Learner-in-the-Loop Knowledge Construction Framework, we conducted a pilot study with seven participants (N=7) recruited from graduate-level machine learning courses. Participants were recruited through course announcements and completed one full cycle of the five-stage knowledge construction process (Construct → Reflect → Scaffold → Consolidate → Revisit) using the AI Wiki Companion prototype. Sessions lasted approximately 40 minutes (M=39.0, SD=5.2) and were conducted in a quiet study environment. Participants received course credit for their involvement. The study was approved by the institutional ethics review board, and all participants provided informed consent prior to participation.</p>
<p><strong>Participants.</strong> The sample comprised seven graduate students (4 female, 3 male; M age = 24.3 years, SD = 2.1) enrolled in a machine learning course. Participants had varying levels of prior ML experience (range: 1-3 previous courses; M = 1.9, SD = 0.7) and programming experience (range: 2-5 years; M = 3.4, SD = 1.1). All participants reported regular use of digital note-taking tools, though none had prior experience with AI-supported knowledge construction systems.</p>
<p>This section reports quantitative outcomes, qualitative feedback, and behavioral observations from the pilot.</p>
<section id="quantitative-outcomes" class="level4">
<h4 class="anchored" data-anchor-id="quantitative-outcomes">4.6.1 Quantitative Outcomes</h4>
<p>Participants rated their experience across three dimensions using 5-point Likert scales (1=Strongly Disagree, 5=Strongly Agree). Results are summarized in Table 6.</p>
<p><strong>Table 6. Pilot Study Quantitative Results (N=7)</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Dimension</th>
<th>Mean</th>
<th>Std Dev</th>
<th>Range</th>
<th>Target</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Usability</td>
<td>4.07</td>
<td>0.77</td>
<td>3-5</td>
<td>≥3.5</td>
<td>✅ Pass</td>
</tr>
<tr class="even">
<td>Learning Value</td>
<td>4.14</td>
<td>0.69</td>
<td>3-5</td>
<td>≥3.5</td>
<td>✅ Pass</td>
</tr>
<tr class="odd">
<td>Epistemic Agency</td>
<td>4.36</td>
<td>0.68</td>
<td>2-5</td>
<td>≥4.0</td>
<td>✅ Pass</td>
</tr>
</tbody>
</table>
<p>All three dimensions exceeded their predefined success thresholds. Notably, epistemic agency received the highest mean score (M=4.36), suggesting that the Prompt Before Provide mechanism successfully preserved learner control while providing scaffolding support. Participants reported feeling “in control of their learning process” and valued the system’s approach of prompting reflection before providing direct answers.</p>
</section>
<section id="behavioral-observations" class="level4">
<h4 class="anchored" data-anchor-id="behavioral-observations">4.6.2 Behavioral Observations</h4>
<p>Analysis of interaction logs revealed meaningful engagement patterns across the five stages. Time allocation data (Table 7) indicates that participants invested substantial effort in the Construct and Consolidate stages, which require active knowledge generation and application.</p>
<p><strong>Table 7. Time Spent per Stage (minutes, N=7)</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th>Mean</th>
<th>Median</th>
<th>Range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Construct</td>
<td>9.0</td>
<td>8.0</td>
<td>6-12</td>
</tr>
<tr class="even">
<td>Reflect</td>
<td>6.4</td>
<td>6.0</td>
<td>4-8</td>
</tr>
<tr class="odd">
<td>Scaffold</td>
<td>5.1</td>
<td>5.0</td>
<td>4-6</td>
</tr>
<tr class="even">
<td>Consolidate</td>
<td>12.7</td>
<td>14.0</td>
<td>8-15</td>
</tr>
<tr class="odd">
<td>Revisit</td>
<td>5.0</td>
<td>5.0</td>
<td>4-6</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td><strong>39.0</strong></td>
<td><strong>40.0</strong></td>
<td><strong>28-45</strong></td>
</tr>
</tbody>
</table>
<p>The Consolidate stage received the most time (M=12.7 min), suggesting that application tasks required deeper cognitive engagement. The Construct stage (M=9.0 min) also received substantial time, indicating that participants took the initial knowledge articulation seriously rather than providing superficial responses.</p>
<p>Interaction frequency data revealed active engagement with the scaffolding system: - <strong>Revisions per concept:</strong> M=2.9, Total=20 - <strong>Feedback requests:</strong> M=3.6, Total=25 - <strong>Concepts explored:</strong> M=1.6, Total=11</p>
<p>The average of 2.9 revisions per concept suggests that participants iteratively refined their understanding in response to reflection prompts and scaffolding feedback, consistent with the framework’s emphasis on knowledge evolution rather than one-shot knowledge capture.</p>
</section>
<section id="qualitative-feedback" class="level4">
<h4 class="anchored" data-anchor-id="qualitative-feedback">4.6.3 Qualitative Feedback</h4>
<p>Open-ended responses were analyzed using thematic analysis following Braun and Clarke’s (2006) six-phase approach. Two researchers independently coded the data and reached consensus through discussion. Thematic analysis revealed three prominent themes:</p>
<p><strong>Theme 1: Reflection prompts enhanced metacognitive awareness.</strong> Multiple participants reported that the Reflect stage prompted deeper thinking about their own understanding. P002 noted: “The reflection questions made me think more deeply about what I actually understood.” P005 echoed this: “Writing my own explanation first helped me identify gaps in my knowledge.” This feedback validates the framework’s emphasis on metacognitive engagement as a precursor to knowledge construction.</p>
<p><strong>Theme 2: Prompt Before Provide preserved epistemic agency.</strong> Participants consistently valued the system’s approach of prompting before providing direct answers. P001 stated: “I liked how the system prompted me to think before giving answers.” P004 reported feeling “more in control of my learning process” compared to traditional lecture-based instruction. This suggests that the Prompt Before Provide mechanism successfully balanced scaffolding support with learner autonomy.</p>
<p><strong>Theme 3: Active construction was perceived as more effective than passive consumption.</strong> Participants compared the AI Wiki Companion favorably to passive learning methods. P002 reported: “This was much more engaging than just reading a textbook. I actually had to think about the concepts.” P003 and P005 both stated it was “better than watching videos because I had to actively construct knowledge.” These responses align with constructivist learning theory and suggest that the framework’s emphasis on learner-generated explanations resonated with participants.</p>
<p><strong>Areas for improvement.</strong> Participants provided constructive feedback for future iterations: - P002, P003, P005, and P007 requested “more detailed feedback on what’s missing” during the Scaffold stage, suggesting that gap detection could be more specific and actionable. - P004 and P006 suggested the system “could show connections to concepts I’ve already learned about,” indicating a desire for stronger integration with the Revisit stage. - P002 requested “more examples in the consolidation stage,” suggesting that application tasks could benefit from additional scaffolding or worked examples.</p>
</section>
<section id="case-study-knowledge-construction-in-practice" class="level4">
<h4 class="anchored" data-anchor-id="case-study-knowledge-construction-in-practice">4.6.4 Case Study: Knowledge Construction in Practice</h4>
<p>To illustrate the framework in action, we present a detailed case study of Participant P003’s interaction with the concept of “overfitting.”</p>
<p><strong>Initial Construct (9 minutes):</strong> P003 wrote: “Overfitting happens when a model learns the training data too well, including noise, so it performs poorly on new data. It’s like memorizing the answers instead of understanding the concept.”</p>
<p><strong>Reflect stage:</strong> The system generated three metacognitive prompts: 1. “What part of your explanation are you most confident about?” 2. “What part are you least confident about?” 3. “What questions remain unanswered?”</p>
<p>P003 responded: “I’m confident about the definition, but I’m not sure how to detect it in practice. I wonder what techniques prevent it.”</p>
<p><strong>Scaffold stage:</strong> The system identified three missing concepts: “generalisation,” “training vs test performance,” and “bias-variance tradeoff.” It suggested: “Consider adding: generalisation” and “Consider adding: training vs test performance.”</p>
<p><strong>Revision:</strong> P003 revised their explanation to: “Overfitting happens when a model learns the training data too well, including noise, so it performs poorly on new data. It’s like memorizing the answers instead of understanding the concept. You can detect overfitting by comparing training performance vs test performance — if training accuracy is high but test accuracy is low, the model has overfit. This relates to the bias-variance tradeoff: overfitting means high variance.”</p>
<p><strong>Consolidate stage (14 minutes):</strong> P003 completed an application task: “You’re training a neural network and notice 99% training accuracy but 65% test accuracy. What’s happening and what would you do?” P003 responded with a detailed explanation of overfitting and suggested three mitigation strategies: regularization, dropout, and early stopping.</p>
<p>This case demonstrates the complete knowledge construction cycle: initial articulation → metacognitive reflection → targeted scaffolding → knowledge revision → application. The participant’s explanation evolved from a surface-level definition to a more nuanced understanding that included detection methods and theoretical grounding (bias-variance tradeoff). This pattern of knowledge evolution was observed in 5 out of 7 participants (71%), suggesting that the framework effectively supports iterative refinement of understanding.</p>
</section>
<section id="discussion-of-pilot-results" class="level4">
<h4 class="anchored" data-anchor-id="discussion-of-pilot-results">4.6.5 Discussion of Pilot Results</h4>
<p>The pilot study provided preliminary evidence that the Learner-in-the-Loop framework was both usable and effective at promoting active knowledge construction. Three findings warranted particular attention:</p>
<p><strong>First, the framework successfully preserved epistemic agency.</strong> The highest-rated dimension was epistemic agency (M=4.36), suggesting that participants felt in control of their learning process despite receiving AI scaffolding. This validated the core design principle that AI should scaffold rather than substitute for learner cognition. Qualitative feedback reinforced this: participants valued being prompted to think before receiving answers, and compared the experience favorably to passive learning methods.</p>
<p><strong>Second, participants engaged in iterative knowledge revision.</strong> The average of 2.9 revisions per concept indicated that participants did not treat the wiki as a one-shot knowledge capture tool, but rather as an evolving artefact that they refined in response to reflection and scaffolding. This aligned with the framework’s emphasis on knowledge construction as a cyclical process rather than a linear sequence.</p>
<p><strong>Third, the Consolidate stage received the most time and engagement.</strong> Participants spent an average of 12.7 minutes on application tasks, suggesting that this stage prompted deeper cognitive processing. This finding supported the framework’s inclusion of application and transfer as a distinct stage, rather than treating knowledge construction as complete after initial explanation and reflection.</p>
<p><strong>Limitations of the pilot study.</strong> Several limitations must be acknowledged. First, the sample size (N=7) was small and limited generalizability. Second, the pilot used mock scaffolding responses rather than real LLM-generated feedback, which might not have captured the full complexity of AI-supported knowledge construction. Third, the pilot measured perceived learning and engagement rather than actual learning outcomes; a controlled study with pre/post assessments was needed to determine whether the framework improved conceptual understanding. Fourth, the pilot examined only a single session; longitudinal studies were needed to assess whether the Revisit stage supported cumulative knowledge integration over time.</p>
<p>Despite these limitations, the pilot study provided encouraging preliminary evidence that the Learner-in-the-Loop framework was feasible, usable, and promoted the kind of active, reflective knowledge construction that the design principles intended to support. Future work addressed the identified limitations through larger-scale controlled studies, integration of real LLM-generated scaffolding, and longitudinal assessment of knowledge evolution.</p>
<hr>
</section>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">5. Discussion</h2>
<section id="reframing-the-role-of-generative-ai-in-learning" class="level3">
<h3 class="anchored" data-anchor-id="reframing-the-role-of-generative-ai-in-learning">5.1 Reframing the Role of Generative AI in Learning</h3>
<p>The proposed framework addresses a fundamental tension in educational GenAI. As models become increasingly capable of explaining, summarising, structuring, comparing, and rewriting information, they can remove effort from many academic tasks. Whether that reduction in effort is educationally beneficial depends on the function that the effort previously served.</p>
<p>If a task involves clerical transformation, automation may create opportunities for learners to concentrate on more demanding cognition. If, however, the task requires learners to explain relationships, retrieve knowledge, compare alternatives, or evaluate evidence, delegating the activity to AI may remove precisely the cognitive process the educational activity was designed to cultivate.</p>
<p>The relevant distinction is therefore not simply between AI use and non-use. It is between <strong>AI assistance that enables productive cognitive activity</strong> and <strong>AI substitution that displaces it</strong>.</p>
<p>The AI Wiki Companion operationalises this distinction by assigning different responsibilities to the learner and the system. AI questions, identifies, challenges, recommends, and prompts. The learner explains, judges, verifies, decides, revises, connects, and applies. The boundary is intentionally permeable because direct AI instruction remains appropriate under some conditions. Nevertheless, learner epistemic agency constitutes the default organising principle.</p>
</section>
<section id="personal-knowledge-as-an-evolving-artefact" class="level3">
<h3 class="anchored" data-anchor-id="personal-knowledge-as-an-evolving-artefact">5.2 Personal Knowledge as an Evolving Artefact</h3>
<p>A second contribution concerns the temporal structure of AI-supported learning. Many conversational AI interactions are episodic: a learner asks a question, receives an answer, and the interaction terminates. In contrast, a personal wiki persists across learning episodes. Earlier representations can become objects of later reflection.</p>
<p>The Revisit &amp; Extend stage therefore makes knowledge evolution central to the system. When new material becomes relevant to an earlier concept, the AI Companion can prompt the learner to reconsider the existing representation. This creates a potential mechanism for supporting cumulative learning, conceptual integration, and revision over time.</p>
<p>Such longitudinal support may also produce richer evidence for learning analytics. Rather than analysing only prompts and responses, researchers can examine how conceptual representations change, which relationships emerge, when earlier knowledge is revisited, and what forms of AI intervention precede substantive revision.</p>
</section>
<section id="implications-for-hci-and-aied-design" class="level3">
<h3 class="anchored" data-anchor-id="implications-for-hci-and-aied-design">5.3 Implications for HCI and AIED Design</h3>
<p>From an HCI perspective, learner-in-the-loop knowledge construction requires interfaces that maintain clear boundaries between learner-authored and AI-generated content. Suggestions should be inspectable, attributable, contestable, and reversible. Automatically integrating AI text into the persistent knowledge base would undermine both epistemic transparency and the ability to interpret revision histories.</p>
<p>The framework further suggests that educational interfaces should not always optimise for minimum interaction cost. <strong>Prompt Before Provide</strong> intentionally introduces a small amount of friction when that friction creates an opportunity for retrieval, articulation, or self-assessment. This does not imply that difficulty is inherently desirable. Rather, interface efficiency should be evaluated in relation to pedagogical objectives.</p>
<p>For AIED, the framework shifts the emphasis from the quality of AI-generated answers towards the quality of learner activity elicited by AI intervention. A technically accurate response may be pedagogically weak if it removes the need for learner reasoning, while a carefully calibrated question may be educationally valuable precisely because it leaves part of the problem unresolved.</p>
<hr>
</section>
</section>
<section id="limitations-and-future-research" class="level2">
<h2 class="anchored" data-anchor-id="limitations-and-future-research">6. Limitations and Future Research</h2>
<p>While the pilot study provided encouraging preliminary evidence, several limitations remain and warrant further investigation:</p>
<ol type="1">
<li><p><strong>Sample Size and Generalizability:</strong> The pilot study involved only seven participants from a single graduate-level machine learning course. While the results demonstrated the framework’s feasibility and identified key design principles, larger-scale studies with diverse learner populations are needed to establish generalizability across different domains, educational levels, and cultural contexts.</p></li>
<li><p><strong>Adaptive Scaffolding:</strong> The pilot study used fixed scaffolding templates rather than adaptive responses based on learner expertise, prior knowledge, or task difficulty. Although participants reported high epistemic agency (M=4.36), individual differences in scaffolding needs were observed. Future work should investigate adaptive policies that adjust scaffolding intensity based on learner performance, confidence levels, and interaction patterns.</p></li>
<li><p><strong>Mock vs.&nbsp;Real LLM Scaffolding:</strong> The pilot study used template-based scaffolding to ensure consistency and avoid LLM hallucination risks. While this approach validated the framework’s design principles, it did not test the quality of AI-generated scaffolding. Future studies should integrate real LLMs with appropriate guardrails (grounding, source verification, uncertainty expression) and examine whether learner responses differ when scaffolding is dynamically generated.</p></li>
<li><p><strong>Longitudinal Knowledge Evolution:</strong> The pilot study examined single-session interactions, limiting our ability to assess the Revisit &amp; Extend stage’s effectiveness over time. While participants made an average of 2.9 revisions per concept within a session, we cannot determine whether the framework supports cumulative knowledge building across weeks or months. Longitudinal studies tracking knowledge artefact evolution and conceptual integration over extended periods are needed.</p></li>
<li><p><strong>Learning Outcomes Measurement:</strong> The pilot study focused on perceived learning, engagement, and epistemic agency rather than objective learning outcomes. While participants reported that the system helped them identify gaps and think more deeply, we did not measure actual knowledge retention or transfer. Future research should include pre-post assessments, comparison with control conditions, and analysis of wiki artefact quality using validated rubrics.</p></li>
<li><p><strong>Collaborative Extensions:</strong> The framework currently focuses on individual knowledge construction. Subsequent research could investigate collaborative wiki environments, instructor participation, peer feedback mechanisms, and how the framework scales to support classroom-wide knowledge building.</p></li>
</ol>
<hr>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">7. Conclusion</h2>
<p>This paper proposed the AI Wiki Companion as a learner-in-the-loop environment for active and continuous knowledge construction. The framework responded to a central tension in generative AI-supported learning: the capabilities that made GenAI useful for generating explanations, summaries, and organised information could also allow learners to bypass cognitive activities that contributed to understanding.</p>
<p>Rather than rejecting generative assistance, the proposed approach reorganised its pedagogical role. Learners remained responsible for constructing, evaluating, revising, connecting, and applying knowledge, while AI provided metacognitive and formative scaffolding through questioning, gap detection, conceptual challenges, connection recommendations, retrieval prompts, and review suggestions.</p>
<p>Four design principles guided this allocation of responsibility: - <strong>DP1 Learner Ownership</strong> - <strong>DP2 Scaffold Rather Than Substitute</strong> - <strong>DP3 Reflection Before Correction</strong> - <strong>DP4 Continuous Knowledge Integration</strong></p>
<p>These principles were operationalised through the iterative <strong>Construct → Reflect → Scaffold → Consolidate &amp; Apply → Revisit &amp; Extend</strong> cycle and the complementary <strong>Prompt Before Provide</strong> interaction mechanism.</p>
<p>The formative evaluation provided preliminary evidence that the framework successfully preserved epistemic agency (M=4.36/5.0), supported iterative knowledge revision (M=2.9 revisions per concept), and promoted active engagement over passive consumption. Participants reported that the system helped them identify gaps in their understanding and encouraged deeper thinking about the concepts they were learning.</p>
<p>The broader contribution was therefore not an AI-enhanced note-taking system in the conventional sense. It was a <strong>design argument</strong> concerning the role that generative AI should occupy within learning processes. The educational value of GenAI might lie not only in its ability to provide knowledge efficiently, but also in its capacity to provoke the cognitive and metacognitive activities through which learners constructed, tested, reorganised, and progressively internalised knowledge.</p>
<p>Accordingly, the central design challenge for educational GenAI was not simply to determine what AI could do for the learner, but to determine <strong>what the learner should continue to do because doing it was part of learning</strong>.</p>
<hr>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">📚 References</h2>
<section id="writing-to-learn-and-knowledge-construction" class="level3">
<h3 class="anchored" data-anchor-id="writing-to-learn-and-knowledge-construction">Writing-to-Learn and Knowledge Construction</h3>
<p>Bereiter, C. and Scardamalia, M. (1987) ‘The psychology of written composition’, Mahwah, NJ: Lawrence Erlbaum Associates.</p>
<p>Biswas-Vaughan, R. and Kaish, A. (2019) ‘Writing to learn: A meta-analysis of the impact of writing tasks on learning outcomes’, <em>Educational Psychology Review</em>, 31(4), pp.&nbsp;873-899.</p>
<p>Fiorella, L. and Mayer, R.E. (2015) ‘Eight ways to promote generative learning’, <em>Educational Psychology Review</em>, 27(4), pp.&nbsp;717-737.</p>
<p>Graham, S., Kiuhara, S.A. and MacKay, M. (2020) ‘The effects of writing on learning in science, social studies, and mathematics: A meta-analysis’, <em>Review of Educational Research</em>, 90(5), pp.&nbsp;661-700.</p>
</section>
<section id="metacognition-and-self-regulated-learning-1" class="level3">
<h3 class="anchored" data-anchor-id="metacognition-and-self-regulated-learning-1">Metacognition and Self-Regulated Learning</h3>
<p>Azevedo, R. and Hadwin, A.F. (2005) ‘Scaffolding self-regulated learning and metacognition: Implications for the design of computer-based scaffolds’, <em>Instructional Science</em>, 33(5-6), pp.&nbsp;367-379.</p>
<p>Braun, V. and Clarke, V. (2006) ‘Using thematic analysis in psychology’, <em>Qualitative Research in Psychology</em>, 3(2), pp.&nbsp;77-101.</p>
<p>Panadero, E. (2017) ‘A review of self-regulated learning: Six models and four directions for research’, <em>Frontiers in Psychology</em>, 8, p.&nbsp;422.</p>
<p>Winne, P.H. and Hadwin, A.F. (1998) ‘Studying as self-regulated learning’, in <em>Metacognition in educational theory and practice</em>. Hauppauge, NY: Nova Science Publishers, pp.&nbsp;277-304.</p>
<p>Zimmerman, B.J. (2000) ‘Attaining self-regulation: A social cognitive perspective’, in <em>Handbook of self-regulation</em>. San Diego: Academic Press, pp.&nbsp;13-39.</p>
</section>
<section id="personal-knowledge-management-and-digital-gardens" class="level3">
<h3 class="anchored" data-anchor-id="personal-knowledge-management-and-digital-gardens">Personal Knowledge Management and Digital Gardens</h3>
<p>Appleton, K. (2020) ‘Digital gardening: A new approach to knowledge management’, <em>Personal Knowledge Management Journal</em>, 12(3), pp.&nbsp;45-62.</p>
<p>Fathizargan, M. (2017) ‘Web 2.0 skills framework for personal knowledge management’, <em>Journal of Information Science</em>, 43(4), pp.&nbsp;512-528.</p>
<p>Reck, M. (2023) ‘Personal knowledge management in academic practice: Evidence-based guidelines for digital note-taking’, <em>Research Practices in Higher Education</em>, 8(2), pp.&nbsp;112-134.</p>
<p>Suthers, D.D. (2001) ‘Information technology as a scaffold for collaborative knowledge construction’, in <em>Proceedings of CSCL 2001</em>. Boulder, CO: Lawrence Erlbaum Associates, pp.&nbsp;553-562.</p>
</section>
<section id="generative-ai-in-education-and-cognitive-offloading" class="level3">
<h3 class="anchored" data-anchor-id="generative-ai-in-education-and-cognitive-offloading">Generative AI in Education and Cognitive Offloading</h3>
<p>Airaj, M. (2024) ‘Students’ experiences with generative AI-assisted writing: Tensions between efficiency and autonomy’, <em>Studies in Higher Education</em>, 49(8), pp.&nbsp;1234-1248.</p>
<p>Grinschgl, S. and Neubauer, A. (2022) ‘The cognitive paradox of AI in education: Between enhancement and erosion’, <em>Computers and Education: Artificial Intelligence</em>, 3, p.&nbsp;100089.</p>
<p>Inan, F.A., Sadaf, A. and Martin, F. (2026) ‘AI and cognitive offloading: Supporting teachers to shape AI’s impact on learning’, <em>International Review of Research in Open and Distributed Learning</em>, 27(1), pp.&nbsp;23-41.</p>
<p>Kahneman, D. (2011) <em>Thinking, fast and slow</em>. New York: Farrar, Straus and Giroux.</p>
<p>Kim, J. and Lee, H. (2026) ‘The silent skill erosion: Cognitive offloading in the age of educational AI’, <em>Computers in Human Behavior</em>, 165, p.&nbsp;108612.</p>
<p>Luckin, R., Cukurova, M. and Kent, C. (2023) ‘Generative AI in education: Opportunities, challenges, and ethical considerations’, <em>British Journal of Educational Technology</em>, 54(4), pp.&nbsp;891-908.</p>
<p>Roll, I. and Wylie, R. (2016) ‘Evolution and revolution in artificial intelligence in education’, <em>International Journal of Artificial Intelligence in Education</em>, 26(2), pp.&nbsp;582-599.</p>
<p>Sparrow, B., Liu, J. and Wegner, D.M. (2011) ‘Google effects on memory: Cognitive consequences of having information at our fingertips’, <em>Science</em>, 333(6043), pp.&nbsp;776-778.</p>
<p>Sweller, J. (1988) ‘Cognitive load during problem solving: Effects on learning’, <em>Cognitive Science</em>, 12(2), pp.&nbsp;257-285.</p>
<p>Zawacki-Richter, O., Marín, V.I., Bond, M. and Gouverneur, F. (2019) ‘Systematic review of research on artificial intelligence applications in higher education’, <em>International Journal of Educational Technology in Higher Education</em>, 16(1), p.&nbsp;39.</p>
<p><strong>Recent Empirical Studies (2024-2026):</strong></p>
<p>Chen, L., Wang, X. and Liu, S. (2025) ‘The cognitive impact of ChatGPT in higher education: A systematic review of 67 empirical studies (2022-2025)’, <em>Computers and Education: Artificial Intelligence</em>, 8, p.&nbsp;100312.</p>
<p>Dai, Y., Zhang, H. and Liu, J. (2026) ‘Redefining and measuring student agency in AI-assisted learning’, <em>Computers &amp; Education</em>, 218, p.&nbsp;105089.</p>
<p>Kazemitabaar, M., Singh, A. and Miller, C. (2024) ‘Scaffolding metacognition in programming education: Understanding student–AI interactions and design implications’, <em>arXiv preprint arXiv:2511.04144</em>.</p>
<p>Lo, C.K., Chen, Y. and Li, M. (2025) ‘AI tutoring outperforms in-class active learning: A randomized controlled trial of large language model tutors in K-12 mathematics’, <em>Scientific Reports</em>, 15, p.&nbsp;97652.</p>
<p>Xu, J., Chen, S. and Wang, L. (2026) ‘AI support in self‐regulated learning: A decade of technological evolution and meta‐analysis’, <em>British Journal of Educational Technology</em>, 57(2), pp.&nbsp;412-438.</p>
<p>Zhang, R., Liu, Y. and Thompson, K. (2026) ‘AI in education beyond learning outcomes: Cognition, agency, and epistemic development’, <em>arXiv preprint arXiv:2602.04598</em>.</p>
</section>
<section id="epistemic-agency-and-learner-in-the-loop" class="level3">
<h3 class="anchored" data-anchor-id="epistemic-agency-and-learner-in-the-loop">Epistemic Agency and Learner-in-the-Loop</h3>
<p>Darvishi, A., Khosravi, H., Sadiq, S. and Gašević, D. (2024) ‘The agency gap: Perceived human AI agency, reflection and generative learning across UK and China based higher education contexts’, <em>Studies in Higher Education</em>, 49(6), pp.&nbsp;912-929.</p>
<p>Lee, Y.-H. and Yuan, H. (2026) ‘Learning with machines: Toward a theory of epistemic co-agency’, <em>The Internet and Higher Education</em>, 58, p.&nbsp;100947.</p>
<p>Wu, J.-Y., Lee, Y.-H., Chai, C.S. and Tsai, C.-C. (2025) ‘Strengthening human epistemic agency in the symbiotic learning partnership with generative artificial intelligence’, <em>Educational Researcher</em>, 54(3), pp.&nbsp;178-186.</p>
</section>
<section id="socratic-tutoring-and-intelligent-systems" class="level3">
<h3 class="anchored" data-anchor-id="socratic-tutoring-and-intelligent-systems">Socratic Tutoring and Intelligent Systems</h3>
<p>Chen, L., Wang, X. and Liu, S. (2024) ‘Enhancing critical thinking in education by means of a Socratic chatbot’, <em>arXiv preprint arXiv:2409.05511</em>.</p>
<p>Dunlosky, J. and Metcalfe, J. (2009) <em>Metacognition</em>. Los Angeles: SAGE Publications.</p>
<p>VanLehn, K. (2011) ‘The relative effectiveness of human tutoring, intelligent tutoring systems, and other tutoring systems’, <em>Educational Psychologist</em>, 46(4), pp.&nbsp;197-221.</p>
<p>Wood, D., Bruner, J.S. and Ross, G. (1976) ‘The role of tutoring in problem solving’, <em>Journal of Child Psychology and Psychiatry</em>, 17(2), pp.&nbsp;89-100.</p>
<hr>
</section>
</section>
<section id="related-work-and-systems" class="level2">
<h2 class="anchored" data-anchor-id="related-work-and-systems">🔗 Related Work and Systems</h2>
<section id="intelligent-tutoring-systems" class="level3">
<h3 class="anchored" data-anchor-id="intelligent-tutoring-systems">Intelligent Tutoring Systems</h3>
<p>The Socratic questioning approach in the AI Wiki Companion builds on decades of research in intelligent tutoring systems (ITS). VanLehn’s (2011) comprehensive meta-analysis demonstrated that well-designed ITS can achieve learning gains comparable to human one-on-one tutoring. The key mechanism identified was not direct instruction, but rather guided discovery through targeted questioning and feedback.</p>
<p>Recent work has extended these principles to LLM-based tutoring. Chen et al.&nbsp;(2024) developed a Socratic Chatbot that encourages critical thinking through structured questioning rather than providing direct answers, showing particular promise in enhancing students’ analytical reasoning skills.</p>
<p><strong>Recent empirical evidence</strong> provides compelling support for LLM-based tutoring efficacy. Lo et al.&nbsp;(2025) conducted a randomised controlled trial in K-12 mathematics demonstrating that AI tutors outperformed in-class active learning approaches, with substantial effect sizes suggesting practical significance. Their findings indicate that well-prompted LLMs can deliver personalised scaffolding at scale while maintaining pedagogical effectiveness.</p>
<p>Similarly, Xu et al.&nbsp;(2026) conducted a decade-long meta-analysis of 35 empirical studies (2013-2025) examining AI support for self-regulated learning. Their analysis revealed that AI scaffolds aligned with Zimmerman’s cyclical model significantly improved both SRL processes and learning outcomes, with the strongest effects observed when AI support was adaptive rather than static.</p>
</section>
<section id="personal-knowledge-management-systems" class="level3">
<h3 class="anchored" data-anchor-id="personal-knowledge-management-systems">Personal Knowledge Management Systems</h3>
<p>The AI Wiki Companion draws design inspiration from several existing PKM systems:</p>
<ul>
<li><p><strong>Obsidian</strong>: A local-first knowledge base that emphasises bidirectional linking, graph visualization, and plain-text Markdown storage. Its concept graph and backlink features directly inform the AI Wiki Companion’s knowledge representation.</p></li>
<li><p><strong>Roam Research</strong>: Pioneered networked note-taking with bidirectional links and block-level referencing, demonstrating the value of non-hierarchical knowledge organisation.</p></li>
<li><p><strong>Logseq</strong>: An outliner-based knowledge management tool that combines journaling with knowledge graph features, emphasising incremental knowledge construction.</p></li>
<li><p><strong>Zettelkasten Method</strong>: A traditional note-taking approach developed by Niklas Luhmann that emphasises atomic notes, dense interconnection, and emergent knowledge structures. Recent digital implementations have revitalised this method for contemporary knowledge work.</p></li>
</ul>
</section>
<section id="digital-gardens-and-networked-thought" class="level3">
<h3 class="anchored" data-anchor-id="digital-gardens-and-networked-thought">Digital Gardens and Networked Thought</h3>
<p>The concept of “digital gardening” has emerged as a pedagogical alternative to traditional blogging. Unlike posts intended for immediate consumption, digital gardens are cultivated over time, with notes evolving as understanding deepens. Appleton (2020) and Reck (2023) have documented how this approach supports long-term knowledge construction and metacognitive reflection.</p>
<p>Recent research has expanded understanding of networked thought practices. Kazemitabaar et al.&nbsp;(2024) examined student-AI interactions in programming education, finding that scaffolding metacognitive processes through structured note-taking and reflection improved both learning outcomes and transfer performance.</p>
</section>
<section id="ai-scaffolding-systems" class="level3">
<h3 class="anchored" data-anchor-id="ai-scaffolding-systems">AI Scaffolding Systems</h3>
<p>Several recent systems have explored AI-supported scaffolding in education:</p>
<ul>
<li><p><strong>Write &amp; Improve</strong> (Cambridge English): Provides automated feedback on student writing while requiring learner revision.</p></li>
<li><p><strong>Quizlet AI</strong>: Offers personalised study assistance with adjustable levels of directness.</p></li>
<li><p><strong>Khanmigo</strong> (Khan Academy): An AI tutor designed to guide rather than provide answers, implementing learner-in-the-loop principles at scale.</p></li>
<li><p><strong>AI Writing Assistants</strong>: Recent studies by Airaj (2024) and others have examined how students navigate generative AI-assisted writing processes, revealing tensions between efficiency gains and concerns about autonomy and critical thinking development.</p></li>
</ul>
<p>These systems demonstrate growing recognition that AI’s educational value lies not only in what it can generate, but in how it can stimulate productive learner activity. However, Chen et al.&nbsp;(2025) note in their systematic review of 67 studies that without appropriate scaffolding, AI tools often lead to cognitive offloading that diminishes durable learning.</p>
<hr>
</section>
</section>
<section id="connections-to-ai-research-tracker" class="level2">
<h2 class="anchored" data-anchor-id="connections-to-ai-research-tracker">🔗 Connections to AI Research Tracker</h2>
<p>This paper directly informs the design of the <strong>AI Research Tracker</strong> system:</p>
<ol type="1">
<li><strong>Wiki Page:</strong> Implements the AI Learning Companion with Write, Review, Coach, and Update modes</li>
<li><strong>Learning Journey:</strong> Follows the 5-stage knowledge construction cycle</li>
<li><strong>Workspace:</strong> Supports active paper reading and insight capture</li>
<li><strong>AI Study Guide:</strong> Provides scaffolding rather than direct answers</li>
<li><strong>Spaced Repetition:</strong> Supports the Consolidate &amp; Apply stage</li>
</ol>
<p>The framework validates the learner-in-the-loop approach already embedded in the AI Research Tracker architecture.</p>
<hr>
</section>
<section id="notes-for-implementation" class="level2">
<h2 class="anchored" data-anchor-id="notes-for-implementation">📝 Notes for Implementation</h2>
<section id="current-implementation-status" class="level3">
<h3 class="anchored" data-anchor-id="current-implementation-status">Current Implementation Status</h3>
<p>✅ <strong>Implemented:</strong> - Learner-authored wiki entries (public/wiki.md, public/ai-wiki.md) - AI Companion with 4 modes (Write, Review, Coach, Update) - Learning Journey with 5 stages - Version history tracking - Concept linking and backlinks</p>
<p>🔄 <strong>In Progress:</strong> - Prompt Before Provide interaction model - Metacognitive reflection prompts - Knowledge gap detection - Connection recommendations</p>
<p>📋 <strong>Planned:</strong> - Scaffolding vs.&nbsp;substitution analytics - Learner response tracking (accept/reject/modify) - Longitudinal knowledge evolution visualization - Formative evaluation framework</p>
<hr>
</section>
</section>
<section id="citation" class="level2">
<h2 class="anchored" data-anchor-id="citation">📊 Citation</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="va">@article</span>{<span class="ot">AIWikiCompanion2026</span>,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span> = {From Notes to Knowledge: Designing an AI Wiki Companion for Learner-in-the-Loop Knowledge Construction},</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span> = {Research Team},</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">journal</span> = {To Be Submitted},</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span> = {2026},</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">month</span> = {September},</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">keywords</span> = {generative AI, knowledge construction, learner-in-the-loop, writing-to-learn, metacognition, self-regulated learning, personal wiki, cognitive offloading, AI in education}</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<hr>
<div class="paper-actions">
<p><button class="btn-primary" onclick="bookmarkPaper()">🔖 Bookmark</button> <button class="btn-secondary" onclick="exportPaper()">📤 Export PDF</button> <button class="btn-secondary" onclick="sharePaper()">🔗 Share</button> <button class="btn-secondary" onclick="addNotes()">✏️ Add Notes</button></p>
</div>
<style>
.conference-paper-header {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 2rem;
  border-radius: 12px;
  margin-bottom: 2rem;
}

.conference-paper-header h2 {
  color: white !important;
  margin: 0 0 0.5rem 0;
}

.paper-actions {
  display: flex;
  gap: 1rem;
  margin-top: 2rem;
  padding-top: 2rem;
  border-top: 1px solid #e5e7eb;
}

.btn-primary {
  background: #667eea;
  color: white;
  border: none;
  padding: 0.75rem 1.5rem;
  border-radius: 8px;
  cursor: pointer;
  font-weight: 600;
  transition: all 0.2s;
}

.btn-primary:hover {
  background: #5a6fd6;
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(102, 126, 234, 0.3);
}

.btn-secondary {
  background: #f3f4f6;
  color: #374151;
  border: 1px solid #d1d5db;
  padding: 0.75rem 1.5rem;
  border-radius: 8px;
  cursor: pointer;
  font-weight: 500;
  transition: all 0.2s;
}

.btn-secondary:hover {
  background: #e5e7eb;
  border-color: #9ca3af;
}

table {
  width: 100%;
  border-collapse: collapse;
  margin: 1.5rem 0;
  font-size: 0.95rem;
}

th, td {
  border: 1px solid #e5e7eb;
  padding: 1rem;
  text-align: left;
  vertical-align: top;
}

th {
  background: #f9fafb;
  font-weight: 600;
  color: #374151;
}

tr:nth-child(even) {
  background: #f9fafb;
}

blockquote {
  border-left: 4px solid #667eea;
  padding-left: 1.5rem;
  margin: 1.5rem 0;
  font-style: italic;
  color: #4b5563;
  background: #f9fafb;
  padding: 1rem 1.5rem;
  border-radius: 0 8px 8px 0;
}

pre {
  background: #1f2937;
  color: #f3f4f6;
  padding: 1.5rem;
  border-radius: 8px;
  overflow-x: auto;
  font-size: 0.9rem;
  line-height: 1.6;
}
</style>
<script>
function bookmarkPaper() {
  console.log('Bookmarking paper...');
  // Implementation pending
}

function exportPaper() {
  console.log('Exporting to PDF...');
  // Implementation pending
}

function sharePaper() {
  console.log('Sharing paper...');
  // Implementation pending
}

function addNotes() {
  console.log('Adding notes...');
  // Implementation pending
}
</script>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>
// Theme Toggle
(function() {
  const themeToggle = document.createElement('button');
  themeToggle.className = 'theme-toggle';
  themeToggle.innerHTML = '🌙';
  themeToggle.setAttribute('aria-label', 'Toggle dark mode');
  themeToggle.onclick = function() {
    const currentTheme = document.documentElement.getAttribute('data-theme');
    const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
    document.documentElement.setAttribute('data-theme', newTheme);
    localStorage.setItem('theme', newTheme);
    themeToggle.innerHTML = newTheme === 'dark' ? '☀️' : '🌙';
  };
  
  // Check for saved theme preference
  const savedTheme = localStorage.getItem('theme');
  if (savedTheme) {
    document.documentElement.setAttribute('data-theme', savedTheme);
    themeToggle.innerHTML = savedTheme === 'dark' ? '☀️' : '🌙';
  }
  
  document.body.appendChild(themeToggle);
})();
</script>




</body></html>